### ISSUE TITLE
"musica_persona" has more than one primary key

### ISSUE THREAD

**Issue by sarapalacio010** [codingupmyfuture/bootcampduckdb#15]
![Captura de pantalla 2024-10-12 180653](https://github.com/user-attachments/assets/d1b3413b-19f3-46fd-a008-d70c446c509e)

SQL Error: java.sql.SQLException: Parser Error: table "musica_persona" has more than one primary key

Cómo se soluciona este error en el codigo?

**Comment by BioDani** [comment]
Sara, algo similar me pasó, pero lo que pude solucionar definiendo la primary key no en cada atributo sino al final del query, de esta manera:

 PRIMARY KEY ( id_1, id_2) 

No sé si haya otra manera pero puedes intentar esta.

**Comment by ChristYela** [comment]
También tenia ese problema, ya también podría ajustar el nombre mas descriptivo en la FK, podría basarse en el formato de los demás ID de las demás FK, así podría evitar la alerta de esa duplicidad de PK
