### ISSUE TITLE
Creacion de Schema Fiesta Deivis

### ISSUE THREAD

**Issue by Nelson8391** [codingupmyfuture/bootcampduckdb#16]
No he logrado crear el schema para montar la data de la fiesta de Deivis.
No logro crearla dentro de bootcamp.db, no sé cómo se hace y al intentarlo aparte me pide si o si anclarlo a una conexión (un documento en mi pc)
Intenté descargando el código de parranda_deivis_diagrama.ddb de la sesión 6, pero al conectarme me dice que no es un archivo valido para DuckDB
No he podido dar el primer paso para poder crear la bbdd.
Alguna starter guide para poder iniciar? Gracias

**Comment by edopore** [comment]
Compañero intenta con la sentencia 
CREATE SCHEMA 'nombre_del_schema';

**Comment by Nelson8391** [comment]
Si, ya lo hice, pero no encuentro el schema, donde deberia quedar? Literal no se donde buscarlo jaja. Gracias!
![image](https://github.com/user-attachments/assets/e1f12da4-0331-4260-b1d1-036e7eed06db)

**Comment by edopore** [comment]
intenta refrescar la conexión presionando F5 o click derecho y buscas la opción RENOVAR.
DBeaver tiene eso que no muestra cambios cuando se realiza y toca refrescarlo para que los muestre

**Comment by edopore** [comment]
De hecho tu schema aparece dentro de bootcamp que es la base de datos y debajo de educacion que es otro schema como fiesta.

**Comment by JessiGM** [comment]
Compañero no se si ya lo solucionaste, pero lo que pasa es que el archivo que está en Git Hub es como la descripción de las tablas, pero no está como base de datos en si (es decir no es el Query), yo realicé el Query para crearla, no se si te sirva de algo la info.

**Comment by juli-amezquita** [comment]
Hola Nelson, el archivo parranda_deivis_diagrama.ddb es el diagrama de entidad relación que hicimos en clase con el profe. Para poderlo visualizar debes descargarlo y subirlo en esta herramienta https://www.drawdb.app/ Este diagrama te va a servir como guía para crear la base de datos.

**Comment by Nelson8391** [comment]
Hola Jessi, gracias! Cómo subiste las tablas dato a dato? No veo por donde poder importar la data, yo tengo ya las tablas creadas como csv, o txt si tbn sirve

**Comment by JessiGM** [comment]
Yo las creé una por una desde Query y luego toca insertarle datos, pero la verdad no sé si los datos son aleatorios o hay unos específicos.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
