### ISSUE TITLE
Creación de tablas Muchos a Muchos

### ISSUE THREAD

**Issue by PabloGarzonB0** [codingupmyfuture/bootcampduckdb#19]
##  relaciones M X M
Hola a todos, tengo la siguiente ambigüedad que me gustaría resolver, al leer un poco más de la documentos de DuckDB me di cuenta de  que este no soporta directamente las claves foráneas ni la referencia a claves externas mediante  `REFERENCES`. así que el uso de la clausula `REFERENCES` no es muy común de DuckDB, en clases cuando vimos DDL aprendimos a hacer la relaciones de la siguiente manera: (@) 
![image](https://github.com/user-attachments/assets/9185b7ab-cd49-4804-80db-5d15eecb3a29)
Entonces aprendí que solo con simplemente declarar la columna de id (llave primaria ) en ambas tablas es posible definir una relacion lógica.

Ahora si quiero realizar una relacion MxM es suficiente crear la tabla de intersección  por ejemplo de plato_persona de la siguiente manera?
```SQL
CREATE TABLE IF NOT EXISTS parranda.plato_persona(
	id_usuario INT NOT NULL, --LLave primaria y tambien foranea
	id_tipo_plato SMALLINT NOT NULL, -- Llave primaria y tambien foranea
	confirmar VARCHAR(1) NOT NULL CHECK(confirmar IN ('S','N')),
	PRIMARY KEY(id_usuario,id_tipo_plato);
);
 ```

Por otro lado, quería aclarar si hay otra manera de escribir llaves foráneas diferente a como se ve en la parte (@), solo escribiendo el atributo de la clase donde proviene o utilizando FOREIGN KEY(....) o algo así. Estoy muy atento a sus comentarios 👍

**Comment by luisvasv-teck** [comment]
En duck DB solo hay la forma mencionada en la documentación, acá ex explicito de  lo soportado a nivel de constraints
![image](https://github.com/user-attachments/assets/d8d4f8f2-03bd-46f6-932b-5041dae3c031)

https://duckdb.org/docs/sql/constraints.html

si no me equivoco, también puedes poner :

```sql
CREATE TABLE IF NOT EXISTS parranda.plato_persona(
	id_usuario INT NOT NULL EREFERENCES ..., --LLave primaria y tambien foranea
	id_tipo_plato SMALLINT NOT NULL REFERENCES ..., -- Llave primaria y tambien foranea
	confirmar VARCHAR(1) NOT NULL CHECK(confirmar IN ('S','N')),
	PRIMARY KEY(id_usuario,id_tipo_plato),
	REFERENCES tabla...,
	REFERENCES ....

);


```

**Comment by PabloGarzonB0** [comment]
Gracias, ya quedo clara mi duda
