### ISSUE TITLE
Taller 1 (DUCKDB_SQLFECATE_E20_P10) pregunta 9

### ISSUE THREAD

**Issue by joamza** [codingupmyfuture/bootcampduckdb#20]
Alguien tuvo problemas con el punto 9 del primer taller. el boot me indica que mi respuesta a la solución del problema planteado es diferente a la respuesta dada por el boot

![image](https://github.com/user-attachments/assets/0cdab671-862e-4643-937d-bbb90625e469)

pero al compararlas no encuentro la diferencia, puede ser un bug en el boot o estoy omitiendo algo?

**Comment by CarlosHeli** [comment]
Hola. Joamza prueba con eso "'%H:%M:%S.%f'" y utilizar strftime(TIMESTAMP. espero que te sirva

**Comment by joamza** [comment]
Hola @CarlosHeli , si así lo estoy manejando, pero creo que el boot esta comparando también el tipo de datos, por que lo mismo me esta pasando en el ejercicio 12 y 18

**Comment by keljozap** [comment]
Hola @joamza efectivamente el boot está teniendo en cuenta el tipo de dato de la respuesta, y el enunciado está pidiendo la hora. Tal vez esto te ayude https://duckdb.org/docs/sql/data_types/time.

Saludos!
