### ISSUE TITLE
Taller DUCKDB_SQLBBDDFIS_E22_P10 Pregunta 17

### ISSUE THREAD

**Issue by MisterDonFrank** [codingupmyfuture/bootcampduckdb#21]
De acuerdo a los datos que nos entregan, el calculo del número de minutos no da el resultado esperado: 43678440

**Comment by keljozap** [comment]
Hola @MisterDonFrank tienes razón. Ese ejercicio presenta un error y este será corregido en el transcurso del día.
Te invitamos a re-enviar el archivo a partir de mañana para re-calificar tu trabajo.

Saludos!

**Comment by luisvasv-teck** [comment]
Ajuste realizado, te debió llegar el punto corregido (en caso de que hayas enviado el rabajo)
