### ISSUE TITLE
Error de envío trabajos

### ISSUE THREAD

**Issue by edopore** [codingupmyfuture/bootcampduckdb#22]
Buenas tardes, resulta que envío los trabajos como se solicita sin modificar el nombre del archivo al correo electrónico y siempre me responde con este error:
![imagen](https://github.com/user-attachments/assets/0de23b5e-3351-46fa-a2a3-c127e56a94c4)
Gracias.

**Comment by edopore** [comment]
Ya resolví el tema de la entrega de los trabajos. Ahora resulta que aparece este error. El trabajo lo estoy enviando desde el correo electrónico inscrito para el curso.

![image](https://github.com/user-attachments/assets/cacc4668-7621-4197-8aff-696b45cd46d8)

Muchas gracias por su ayuda

**Comment by edopore** [comment]
Aparece en el asunto del correo como entrega inválida

**Comment by PabloGarzonB0** [comment]
Hola @edopore, me paso el mismo problema al enviar mis actividades al bot que evalua los resultados, la razón fue que mientras escribía mis respuestas por accidente moví una celda del notebook (se me cambio de orden), Te recomiendo tomes nuevamente una plantilla pegues tus respuestas en limpio y **no modifiques absolutamente nada**, solo el nombre del archivo como el profe recomendo y en la siguiente entrega debería aceptarte tus respuestas

**Comment by edopore** [comment]
Hola @PabloGarzonB0 mira que hice lo que me sugeriste pero el error sigue presentandose. Pero te agradezco por la solución.

**Comment by keljozap** [comment]
Hola @edopore espero estes bien, como te dijo @PabloGarzonB0 el error está pasando porque el evaluador está notando diferencias entre el archivo que envias y el que se envió. Yo te recomendaria, descargar nuevamente el archivo de telegram y copiar y pegar tus respuestas en el nuevo archivo, recordar agregar el prefijo DUCKDB_ al nombre del archivo antes de enviarlo nuevamente, luego, enviarlo nuevamente y mirar si el error se repite. Si vuelves a tener el error comentanos nuevamente.

Saludos!

**Comment by edopore** [comment]
@keljozap cómo va todo?
Si, hice lo que @PabloGarzonB0 me recomendó, tomé los notebooks del grupo de telegram pero el problema sigue siendo el mismo.
Agradezco su ayuda

**Comment by luisvasv-teck** [comment]
En proceso de ajuste, fecha máxima de solución es 22/10/2024

**Comment by andresgonzalezrpo** [comment]
Tengo el mismo problema, hay que poner algo especial en el asunto, o solo es adjuntar la notebook?

**Comment by luisvasv-teck** [comment]
¡Hola a tod@s!

Lamentamos los inconvenientes. Hemos actualizado la versión de Python (para los developers), lo que ha generado algunos problemas. Ya comenzamos a recalificar los trabajos y he notado que varios ya fueron corregidos. Si alguno de ustedes sigue recibiendo el error list.remove(x): x not in list, por favor vuelvan a enviar sus trabajos para monitoreo.

Agradecemos su apoyo y esperamos que, con las entregas, podamos estabilizar el comportamiento inusual. Quedamos atentos y gracias por su paciencia.
