### ISSUE TITLE
Entorno de trabajo para realizar trabajos

### ISSUE THREAD

**Issue by andresgonzalezrpo** [codingupmyfuture/bootcampduckdb#23]
No me carga la base de datos en google colab, puede ser problema de mi PC, realmente no entiendo bien si puedo usar Visual Studio,
o debido a la estructura de la notebook tiene que ser desarrollado en Colab?
Gracias

**Comment by edopore** [comment]
Compañero como estás?
El desarrollo según entiendo se debe hacer en los notebooks de python. La base de datos se demora en subir y debes subir la base de datos cada que abras el notebook en colab

**Comment by andresgonzalezrpo** [comment]
Pero se demora demasiado, llevo más de 20 minutos y lo he intentado 2 veces, creo que ya no es un tiempo normal, ya puede ser más un tema de recursos del PC

**Comment by andresgonzalezrpo** [comment]
Ya lo resolví, al parecer estaba cargando un archivo dañado. Gracias
