### ISSUE TITLE
Creo que hay un problema en el bot

### ISSUE THREAD

**Issue by andresgonzalezrpo** [codingupmyfuture/bootcampduckdb#24]
Buenas tardes, si uno piensa que el bot tiene un error al calificar o uno no entiende la sugerencia, es posible hablar con el profe o con alguien @luisvasv-teck @codingupmyfuture

**Comment by luisvasv-teck** [comment]
La idea es que documentes este issue y especifiques porque, evidencias y demás para ser evaluado.

**Comment by andresgonzalezrpo** [comment]
Profe te envié un correo pero te voy a poner un ejemplo por aca. a continuación adjunto respuesta del bot en un ejercicio que en mi concepto está bien

![Imagen1](https://github.com/user-attachments/assets/4683c5aa-9fbd-427c-857e-2907240f455e)

**Comment by luisvasv-teck** [comment]
es importante indicar taller y punto, ya que hay más de 100 ejercicios para realizar. Este problema fue resuelto en un issue posterior

**Comment by andresgonzalezrpo** [comment]
Si perfecto, no había entendido la dinámica pero ya lo comprendí, voy a cerrarlo gracias
