### ISSUE TITLE
Dudas sobre los criterios de calificación usados por el bot

### ISSUE THREAD

**Issue by Fenix018** [codingupmyfuture/bootcampduckdb#25]
Me gustaría compartir aquí mis inquietudes y dudas en cuanto a la calificación del bot con respecto a los trabajos; realicé la entrega del trabajo: DUCKDB_SQLFECATE_E20_P10 y no me queda claro los errores señalados en la calificación en cuanto a los puntos 9, 16 y 18. También he encontrado errores en cuanto al 17; en el notebook me piden un resultado pero el bot está evaluando con respecto a otro:
![image](https://github.com/user-attachments/assets/3d1c3ea6-3017-46f6-8324-c30ac09149fd)
![image](https://github.com/user-attachments/assets/154f896c-92f2-466b-b6b2-cfb56a06e484)
![image](https://github.com/user-attachments/assets/8a0421c5-6c28-4498-9c82-0435f6e26056)
![image](https://github.com/user-attachments/assets/4e438cec-d1d6-464d-b979-38f1b0a1be01)
![image](https://github.com/user-attachments/assets/ae0b601b-53a0-47fb-a437-57203d286fec)

**Comment by edopore** [comment]
@Fenix018, según veo tus errores son por el tipo de dato que revisa el bot, 
En el ejercicio 09 debías nombrar la columna con el nombre "hora" pero en tu respuesta no lo hiciste,
tambien el ejercicio 16 el tiene en cuenta que se esté usando la función trim(), por otro lado veo que estás usando TRIM(), esto pasa igual en el ejercicio 18 con la función substring() y posiblemente tu usaste SUBSTRING().
Debido a eso el bot te las calificó malas.

**Comment by Fenix018** [comment]
ahora me confunde el tratar de entender que diferencia hay en cuanto a trim() y TRIM() como para que el punto esté malo.

**Comment by keljozap** [comment]
Hola buenas tardes. Esta es la documentación oficial de DuckDb, la función trim() está escrita en minúscula porque es una función. Generalmente en programación las funciones no son escritas en mayusculas sostenidas.

![image](https://github.com/user-attachments/assets/9587c727-9067-4135-8fd4-9ceb3195fde0)
