### ISSUE TITLE
Duda, DUCKDB_SQLFECATE_E20_P10. Punto 12 y 18

### ISSUE THREAD

**Issue by Jenn0407** [codingupmyfuture/bootcampduckdb#26]
Hola, buenas noches,
Quisiera saber si alguno tiene el mismo inconveniente. 
No entiendo el error que me estan ocasionando el punto 12 y el 18, del primer taller. 
Según yo, están bien, sin embargo, el boot los ha rechazado, si alguno sabe qué puede estar ocasionando el error o qué estoy ignorando, le agradezco mucho su ayuda. 
Adjunto pantallazos. 
Punto 12. Adjunte el pantallazo de la prueba porque mi resultado era igual al esperado, pero no entiendo el de la comparación de control de los resultados. 
![Anotación Boot, Punto 12](https://github.com/user-attachments/assets/9815ef76-bb6f-4b42-9d10-28d23d6ee7cf)
![Comparación Punto 12](https://github.com/user-attachments/assets/1ad8aa46-c060-4690-939b-da2c6c0b3263)
![Mi respuesta en el pnto 12](https://github.com/user-attachments/assets/d3591385-7c79-4d5f-a873-790868c373db)

Punto 18
![Comentario Boot Punto 18](https://github.com/user-attachments/assets/bb0c9c67-3602-4a83-bd64-f767bdd4593e)
![Comparación Punto 18](https://github.com/user-attachments/assets/a9db2980-f0b7-4b14-ae42-bea56eead0ab)

Muchas gracias!

**Comment by Dhmthe** [comment]
@luisvasv-teck me pasa lo mismo que al compañero quedo atento!

**Comment by Jenn0407** [comment]
Compañero, ya lo pude solucionar, en el punto 12 específique el tipo de dato que estaba usando en la sentencia. Y en el 18 organice la posición para extraer los caracteres. 
Espero que estas respuestas te ayude a organizar las tuyas.
