### ISSUE TITLE
Errores en calificación pregunta 9 y 12 en taller DUCKDB_SQLBBDDFIS_E22_P10

### ISSUE THREAD

**Issue by Dhmthe** [codingupmyfuture/bootcampduckdb#27]
Envío las respuestas y en google colab me entrega la respuesta bien, pero el bot me califica mal 
ejercicio 9 en google colab
![image](https://github.com/user-attachments/assets/7d4bff92-3f4f-4f7a-be5e-87a04e26dc9f)
también lo realicé de la siguiente forma
![image](https://github.com/user-attachments/assets/94718970-9e30-467b-b02f-53696098c8ff)
Ambos me los califica mal el bot dejo evidencia
![image](https://github.com/user-attachments/assets/33096276-dcfb-4267-8a92-092bfea4b10d)

con el ejercicio 12 me sale el siguiente error 
![image](https://github.com/user-attachments/assets/8d3b5d97-8a18-488e-975c-94f9bcb6b74b)
 En google colab lo estoy llamando tal cual y aun no me lo califica bien el bot

**Comment by dcanosu** [comment]
Hola compañeros, yo también en ambos puntos eh recibido el mismo mensaje del Bot.

# Punto 9
Lo eh enviado de dos formas, pero tampoco me pasa el punto.

```sql
SELECT (1/0.3::FLOAT) resultado;
```
![image](https://github.com/user-attachments/assets/2857308c-b2d6-43e0-b101-0ffdefd124a8)

```sql
SELECT 1 / 0.3 AS resultado;
```
![image](https://github.com/user-attachments/assets/3e60e026-7789-49b0-9972-07b2bb677d07)

### La solución no superó la prueba: Las columnas no concuerdan con las propuestas del control: ['(1 / 0.3)']

# Punto 12

Al parecer no sé si se trata del tipo de dato al ser los números tipo Float que no este aceptando el resultado como DOUBLE al hacer el casteo. Pero el ejercicio lo esta solicitando en DOUBLE

## Attribute "dtype" are different [left]: object [right]: float64

```sql
SELECT
	TRY_CAST(2 * 3.1415 * 7.5 AS DOUBLE) AS perimetro,
	TRY_CAST(3.1415 * 7.5 * 7.5 AS DOUBLE) AS area;
```
![image](https://github.com/user-attachments/assets/13271713-e268-4c3a-b518-18f8ff33812f)
![image](https://github.com/user-attachments/assets/a25418fb-5c46-4057-ae1f-939baa143d8d)

**Comment by charliesalcedo** [comment]
Buenas tardes, 

Les comparto para el punto 9 lo que encontré: basicamente el bot tiene errores en sus controles y en la manera cómo como evalua.

Si detallan el control que muestra en la retroalimentación para este caso está comparando que tenga un (1/0.3) y no el encabezado "resultado" cómo lo pedia en el enunciado del notebook de Google Coolab.

Les comparto el código que utilicé y con el cual me marcó como correcto el punto, que si bien es un error es la manera de que funciona.
![image](https://github.com/user-attachments/assets/63304867-f21f-4f9e-9e30-da38ebb5d6b4)

![image](https://github.com/user-attachments/assets/e27841e8-d7fa-4025-a27d-a6f84553a233)

**Pdta:** he notado que este tipo de situaciones pasan en otros puntos y talleres.

En cuanto al punto 12, aún no he encontrado la solución, ya que he intentado varias opciones y me sigue generando error.
Espero alguien nos pueda compartir su conocimiento de cómo logró solucionarlo!

**Comment by luisvasv-teck** [comment]
El punto 9 ajustado si miran lo que entrega el bot no tenía el alias

![image](https://github.com/user-attachments/assets/f753c861-528c-4d67-ab3b-7f59812c24bc)

**Comment by Dhmthe** [comment]
> El punto 9 ajustado si miran lo que entrega el bot no tenía el alias
> 
> ![image](https://private-user-images.githubusercontent.com/108821097/379838265-f753c861-528c-4d67-ab3b-7f59812c24bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODQ4NTIsIm5iZiI6MTcyOTc4NDU1MiwicGF0aCI6Ii8xMDg4MjEwOTcvMzc5ODM4MjY1LWY3NTNjODYxLTUyOGMtNGQ2Ny1hYjNiLTdmNTk4MTJjMjRiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNTQyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2E0OWViNjA0YzAzZDkwYWM2MTA4NmYyODliZWNmMWRjMDZjZGQxMjVkNmY4MzA3NDgzYzA3N2YyYzJjN2Q5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kQK19sRUPDEsKf58_nQ-8rRMTWUxNoO0qZJ4Pp4AnIc)

Ok entonces segun entiendo debo ponerle el nombre que aparece en control, y con respecto al 12?

**Comment by andresgonzalezrpo** [comment]
parece que en el punto 12 del taller E22_P10 el error es debido a que el bot está esperando tipo object, pero el ejercicio pide ponerlo en DOUBLE, para revisar porfa @luisvasv-teck 
![Imagen3](https://github.com/user-attachments/assets/0d01cbd6-d446-4dbe-a1f4-29079746e349)
por que también tengo mi respuesta igual pero me muestra que el error está en el tipo de dato y yo lo estoy casteando a Double

**Comment by luisvasv-teck** [comment]
Literalmente en la respuesta esperada , miren como están costeando, de hecho no es requerido
![image](https://github.com/user-attachments/assets/6fc7ba56-9fb1-4ca5-8fee-26da2ba5211f)

**Comment by Dhmthe** [comment]
> Buenas tardes,
> 
> Les comparto para el punto 9 lo que encontré: basicamente el bot tiene errores en sus controles y en la manera cómo como evalua.
> 
> Si detallan el control que muestra en la retroalimentación para este caso está comparando que tenga un (1/0.3) y no el encabezado "resultado" cómo lo pedia en el enunciado del notebook de Google Coolab.
> 
> Les comparto el código que utilicé y con el cual me marcó como correcto el punto, que si bien es un error es la manera de que funciona. ![image](https://private-user-images.githubusercontent.com/158254684/379507287-63304867-f21f-4f9e-9e30-da38ebb5d6b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjQxODEsIm5iZiI6MTcyOTgyMzg4MSwicGF0aCI6Ii8xNTgyNTQ2ODQvMzc5NTA3Mjg3LTYzMzA0ODY3LWYyMWYtNGY5ZS05ZTMwLWRhMzhlYmI1ZDZiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwMjM4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTE4NGYyNzQyMDZjNjRlYWQxMDc5N2I3OGNlZmVmNDMwNDE0ZmY4YTg3NDU4N2ViZWExODZhMWIyMWY2Mzc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.idLngWcxb_BCVcBok9mVlDzk4NblzttA8t98-vCT9HM)
> 
> ![image](https://private-user-images.githubusercontent.com/158254684/379507104-e27841e8-d7fa-4025-a27d-a6f84553a233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjQxODEsIm5iZiI6MTcyOTgyMzg4MSwicGF0aCI6Ii8xNTgyNTQ2ODQvMzc5NTA3MTA0LWUyNzg0MWU4LWQ3ZmEtNDAyNS1hMjdkLWE2Zjg0NTUzYTIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwMjM4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjAwZmE5NDZiMzc5YTIwMGJiMzYyMTFlNjk4NGMwMzA0YTdmZGNjZjYxMzQ4MmU0NDFmNzc2M2ZmODk2ODM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B1hUqdtvEgVZ2cLy0gd_OlJFtup3koBy7hc7IXesC-c)
> 
> **Pdta:** he notado que este tipo de situaciones pasan en otros puntos y talleres.
> 
> En cuanto al punto 12, aún no he encontrado la solución, ya que he intentado varias opciones y me sigue generando error. Espero alguien nos pueda compartir su conocimiento de cómo logró solucionarlo!

Aquí viene lo interesante, hice el cambio, pero o sorpresa el bot me lo califico mal porque esperaba resultado, pero si pongo resultado me dice que esperaba él (1/0.3)
![image](https://github.com/user-attachments/assets/643e563e-6e8c-4448-8bb7-133848e55cb3)

**Comment by juli-amezquita** [comment]
Hola @Dhmthe, en el punto 9 ponle el encabezado resultado tal como pide el ejercicio, el bot ya lo está tomando. Hicieron la corrección debido al reporte de nuestros compañeros.
