### ISSUE TITLE
DUCKDB_SQLFECATE_E20_P10.ipynb Errores en calificación puntos 11 - 12 - 16 - 17 y 18

### ISSUE THREAD

**Issue by aguirreaida** [codingupmyfuture/bootcampduckdb#28]
cordial saludo 

la presente es para dar a conocer que el bot me esta calificando mal los ejercicios 11, 12, 16, 17 y 18. No estoy de acuerdo con esta calificaciones, sabiendo que las respuestas están igual a lo que deberían dar.

a continuación adjunto pantallazos.
11
![pregunta 11](https://github.com/user-attachments/assets/4fb8294d-b95a-4330-8a57-c4ec7394c2e0)
12
![pregunta 12](https://github.com/user-attachments/assets/4f0da0ba-d7b1-4ad9-a106-ff6051d37e57)
16
![pregunta 16](https://github.com/user-attachments/assets/246a85e0-de1e-4faf-9019-f5e29cfc1f81)
17
![pregunta 17](https://github.com/user-attachments/assets/a9afe0c7-4d9b-487b-b7ac-f031c0620bc3)
18
![pregunta 18](https://github.com/user-attachments/assets/dd0dbcb2-ff6e-4d07-b6ba-7f50b483a9c4)

Quedo atenta a la solución que me puedan brindar, muchas gracias.

**Comment by luisvasv-teck** [comment]
Recuerda que las tablas de resultados en los ejercicios se colocan de guía de más o menos que se espera en el ejercicio, muchas veces no se entrega el resultado esperado. Ya que lo que se espera se encuentra en el contexto del ejercicio.

Verificando: 

PUNTO 11:  se espera esto`Día de la semana, DD Mes Año - HH:mm:ss AM/PM` y tú le estás agregando palabra` de`
PUNTO 12: efectivamente el control tenía un problema, ya fue solucionado. A la próxima calificación tomará el ajuste
PUNTO 16, 17 y 18: no errores detectados.

**Comment by andresgonzalezrpo** [comment]
En el punto 16 tengo el siguiente problema, dice que el problema es en el alias, en el documento de revisión me lo pone en mayúscula pero yo en mi notebook lo tengo en minúscula, es como si el bot pone en mayúscula mi alias
@luisvasv-teck 
![Imagen5](https://github.com/user-attachments/assets/b11df382-908e-4aaf-863e-dac3fe855f38)


![Imagen6](https://github.com/user-attachments/assets/6dad6885-925a-4083-b78d-40be25ba234f)

igualmente adjunto la descripción del error en el documento de descripción

![Imagen7](https://github.com/user-attachments/assets/fd012d9b-5602-49ff-a6ab-5aec03f2c180)

**Comment by ASzklar** [comment]
Noté lo mismo en el punto 16. Es como que el test de correción modifica el alias a mayúsculas.

**Comment by JenniGomez04** [comment]
Me ocurre lo mismo en el punto 16, en mi google colab aparece como se espera pero el bot no lo toma asi ¿Qué se puede hacer? 

![Issue Respuesta 1](https://github.com/user-attachments/assets/fff8dc17-3714-42e2-8e37-4aa37c705bcc)
