### ISSUE TITLE
Dudas en el taller 3

### ISSUE THREAD

**Issue by andresgonzalezrpo** [codingupmyfuture/bootcampduckdb#29]
Punto 2:
La instrucción dice:
**Guarda el resultado con nombre (AS) ultimos_tres_estudiantes**
parece que hay un inconveniente con el control 
![punto2taller3](https://github.com/user-attachments/assets/2e1fdcaf-ffaa-4f32-b205-9defb22429b0)

También noto una diferencia en las mayúsculas la primera letra pero en mi notebook las tengo correctas

![Imagen4](https://github.com/user-attachments/assets/776342a6-8456-459a-8b09-3361e7f1c8da)

Punto 7

Me dice que hay un error en el código
![Imagen1](https://github.com/user-attachments/assets/b9b3ce6c-ca7d-410c-91a2-02b6f52f5eb7)

en mi notebook todo está bien, por favor revisarlo, adjunto mi resultado

![Imagen2](https://github.com/user-attachments/assets/c98a5aaa-4c99-4686-b2ea-61999d2dddac)

**Comment by afflorezc** [comment]
Tamién existen problemas con la revision del punto 5. La lista que entrega mi query coincide en su totalidad pero la identifica como erronea: 

![image](https://github.com/user-attachments/assets/4ffde402-0c7d-4db7-b09b-864548025d82)

**Comment by andresgonzalezrpo** [comment]
Hola, recueden este issue porfa, este es el taller E18_P20.
Aparte de los 2 inconvenientes que mencione en este taller, tengo problemas con el punto 10.
Hay un bug de compilación.
Ejercicio no superado. Puntuación obtenida: 0.0% Puntuación mínima requerida: 75.0% Debido
a: El ejercicio falló su ejecución debido a: Traceback (most recent call last): File
"/Users/lvasq/miniconda3/envs/ss/lib/python3.10/sitepackages/
pandas/core/arrays/categorical.py", line 460, in __init__ codes, categories =
factorize(values, sort=True) File "/Users/lvasq/miniconda3/envs/ss/lib/python3.10/sitepackages/
pandas/core/algorithms.py", line 795, in factorize codes, uniques = factorize_array(
File "/Users/lvasq/miniconda3/envs/ss/lib/python3.10/site-packages/pandas/core/algorithms.py",
line 595, in factorize_array uniques, codes = table.factorize( File
"pandas/_libs/hashtable_class_helper.pxi", line 7281, in
pandas._libs.hashtable.PyObjectHashTable.factorize File
"pandas/_libs/hashtable_class_helper.pxi", line 7195, in
pandas._libs.hashtable.PyObjectHashTable._unique TypeError: unhashable type: 'dict' During
handling of the above exception, another exception occurred: Traceback (most recent call last):
File "/Users/lvasq/repositories/personal/evaluator/evaluator/src/qualifier/exercise/sql.py", line
293, in _run_exercise (asserts or self._standard_assert)(inputs, output, controls[0]) File
"/Users/lvasq/repositories/personal/evaluator/evaluator/src/qualifier/exercise/sql.py", line 271, in
_standard_assert control.sort_values(by=control_cols, ascending=True).reset_index(drop=True),
File "/Users/lvasq/miniconda3/envs/ss/lib/python3.10/site-packages/pandas/core/frame.py", line
7183, in sort_values indexer = lexsort_indexer( File
"/Users/lvasq/miniconda3/envs/ss/lib/python3.10/site-packages/pandas/core/sorting.py", line
351, in lexsort_indexer cat = Categorical(k, ordered=True) File
"/Users/lvasq/miniconda3/envs/ss/lib/python3.10/sitepackages/
pandas/core/arrays/categorical.py", line 462, in __init__ codes, categories =
factorize(values, sort=False) TypeError: unhashable type: 'dict'

Pero mi respuesta es igual a la esperada.
Gracias
@keljozap 
@luisvasv-teck

**Comment by keljozap** [comment]
Hola @andresgonzalezrpo.

Asumiento que el taller sea el E18_P20
Punto 2: tus resultados están en minúscula y el control en mayúscula empieza cada nombre. Puedes adjuntar tu consulta si consideras que ese no es el error y lo podemos revisar.
Punto 7. Estás tratando de hacer un slide (por lo que se ve) y te hace falta un parámetro que es lo que está diciendo el error. Si tomo tu sentencia y la ejecuto en el DBeaver me sale el mismo error. Esta es tu consulta según el error que adjuntas SELECT (['a', 'b', 'c'])[$1] AS resultado2 y sale este error
![image](https://github.com/user-attachments/assets/b23287f1-7b07-4331-a2f1-bd667a287f75)
Es el mismo error que te está mostrando el calificador, no es error del calificador, es error de tu consulta.

Punto 5. No puedo ver tu query, podrías adjuntarlo aqui para ver que diferente está del calificador? gracias.
Punto 10. No puedo ver tu query, podrías adjuntarlo aqui para ver que diferente está del calificador? gracias.

Saludos!

**Comment by andresgonzalezrpo** [comment]
Gracias @keljozap por tu tiempo,

Punto 2: mi query también inicia con mayúscula, he visto que otros compañeros han reportado el mismo problema.
SELECT ['Ana', 'Luis', 'Carlos', 'María', 'Juan', 'Elena', 'Pedro', 'Sofia', 'Rosa', 'Luis'][-3:] AS ultimo_tres_estudiantes;

Punto 7: En mi notebook funciona perfecto
SELECT ['a', 'b', 'c'][:2] AS resultado2;

Punto 10: En mi notebook funciona perfecto
SELECT MAP {
  'key1': 10,
  'key2': 20,
  'key3': 30
} AS A,
MAP {
  1: 72.01,
  5: -672.10
} AS B

**Comment by keljozap** [comment]
Hola @andresgonzalezrpo 

Punto 2. Entiendo, veo que el query está perfecto pero el ejercicio dice ARRAY y el calificador está intentando calificar que devuelva un tipo array agrega la palabra ARRAY despues del SELECT de tu query y no debería ponerte problema, es lo único que le falta. Es decir SELECT ARRAY['Ana', 'Luis', 'Carlos', 'María', 'Juan', 'Elena', 'Pedro', 'Sofia', 'Rosa', 'Luis'][-3:] AS ultimo_tres_estudiantes; Eso cambiará el tipo de dato retornado.

Punto 7. Intenta con este SELECT (['a', 'b', 'c'])[1:2] AS resultado2, lo único diferente serían los parentesis y tal vez lo esté tomando como un resultado de 3 niveles en vez de dos.

Punto 10. Lo único que veo de diferente en tu query son los espacios después de la coma y antes de cada key, de esta forma SELECT MAP {'key1': 10, 'key2': 20, 'key3': 30} AS A, MAP {1: 72.01, 5: -672.10} AS B. Si agregando los espacios no te funciona por favor dejamelo saber y pon una imagen del error aqui para saber cual es el error exacto.

Espero esto te ayude.

Saludos!

**Comment by andresgonzalezrpo** [comment]
Me sirvieron todas tus recomendaciones @keljozap 
Muchas gracias
