### ISSUE TITLE
Error: current transaction is aborted (please ROLLBACK)

### ISSUE THREAD

**Issue by AlejandroEnciso7** [codingupmyfuture/bootcampduckdb#30]
Hola, alguien sabe por qué me sigue saliendo este error cuando intento correr las query?  
![image_2024-10-24_133211060](https://github.com/user-attachments/assets/fa8dcbf9-d3a6-427f-8048-31bca56b496d)

Solo me deja correr un intento de alguna query y quede bien o mal al siguiente me sale el error y debo desconectarme y reconectarme para poder volver a correr una query nueva. Entonces en un taller de 20 puntos me toca literal desconectarme y conectarme 20 veces.

Gracias de antemano por alguna solución que tengan!

**Comment by juli-amezquita** [comment]
Hola @AlejandroEnciso7, las veces que me ha pasado, lo único que he hecho es volver a correr la primera celda del taller y ya con eso vuelve a funcionar todo, obviamente debes corregir el error porque te vuelve a pasar lo mismo, pero como te digo es solo volver a correr la primera celda. Espero te funcione a ti también.
