### ISSUE TITLE
Duda SQLBBDDFIS Ejercicio área y perimetro

### ISSUE THREAD

**Issue by BioDani** [codingupmyfuture/bootcampduckdb#31]
Saludos, Compañeros. 

Quisiera saber si alguno de ustedes ha experimentado el error en el ejercicio del perimetro y área del circulo. En mi caso me encuentro que a pesar de que todo se ve aparentemente igual el bot califica incorrecta mi respuesta. 

¿Tienen idea si quizá es requerido un casteo en particular que no está definido en el enunciado? 

Muchas gracias por sus aportes. 

![Screenshot 2024-10-24 at 8 07 43 PM](https://github.com/user-attachments/assets/001c76a0-3876-4092-a609-6d450e484587)

**Comment by juli-amezquita** [comment]
Hola @BioDani la pregunta 12 del cálculo del perímetro y área de un círculo pide que se utilice el tipo DOUBLE. Creo que con eso deberías poder solucionar.

**Comment by JikaS14** [comment]
Yo cumplo hasta con el tipo sugerido DOUBLE y aun así me califico mal, me pregunto si el salto de linea tendra que ver.
