### ISSUE TITLE
El robot no me está calificando los trabajos

### ISSUE THREAD

**Issue by malalalalala** [codingupmyfuture/bootcampduckdb#34]
Ayer envié dos trabajos desde mi correo  con los archivos con el mismo nombre al correo coding.up.my.future@gmail.com y no me ha calificado aún.

**Comment by luisvasv-teck** [comment]
La herramienta de calificación automática solo acepta archivos en formato .`ipynb (Jupyter Notebook)`, como se explicó en los videos introductorios (más de 2 horas de contenido). El archivo que enviaste está en un formato no compatible (Word o texto plano), lo que impide que sea procesado correctamente.

Por favor, asegúrate de subir el archivo en el formato adecuado. Para más validación, te sugiero revisar la siguiente documentación:


- [000.bienvenida.pdf](https://github.com/codingupmyfuture/bootcampduckdb/blob/main/contenido.curso/002.documentos/000.bienvenida.pdf)
- [001.intro.curso.pdf](https://github.com/codingupmyfuture/bootcampduckdb/blob/main/contenido.curso/002.documentos/001.intro.curso.pdf)
- [video intro](https://github.com/codingupmyfuture/bootcampduckdb/blob/main/contenido.curso/000.recursos/videos/001.intro.curso.txt)
- [ntrega.trabajos](https://github.com/codingupmyfuture/bootcampduckdb/blob/main/contenido.curso/000.recursos/videos/002.entrega.trabajos.txt)

**Comment by malalalalala** [comment]
Gracias por tu respuest. Vi los videos que mencionas e hice lo que ellos indicaban.
![image](https://github.com/user-attachments/assets/92bc690d-9483-4e33-93f3-72743f2d0d78)

**Comment by malalalalala** [comment]
![image](https://github.com/user-attachments/assets/7c9d420f-edba-4542-ae46-e216c695999f)

**Comment by luisvasv-teck** [comment]
Tampoco archivos compartidos:

![image](https://github.com/user-attachments/assets/d4986080-ca19-4f8b-8ae6-4759068074c9)


Por favor seguir la documentación, gracias.
