### ISSUE TITLE
Taller E20 P10

### ISSUE THREAD

**Issue by AlejandroEnciso7** [codingupmyfuture/bootcampduckdb#37]
Pondré aquí varias de las preguntas que tengo, si me pueden ayudar con al menos uno se los agradezco.

1. 
![image](https://github.com/user-attachments/assets/89019ce8-0b89-47c4-8a77-296efbf971ef)
![image](https://github.com/user-attachments/assets/8087e452-e165-4029-927d-83fd83ca1e41)
 
en el punto 8 creo que tanto el error como la comparacion entre control y estudiante me dice que tengo la misma información pero no sé por que no me reconoce la respuesta como correcta?
lo mismo sucede con el punto 15
![image](https://github.com/user-attachments/assets/bf26c6a6-a163-4320-86f6-af9132832f14)

2.
En los puntos 13 y 14, no entiendo que es lo que este pidiendo el bot, segun eso la respuesta es un numero con exponente 18
![image](https://github.com/user-attachments/assets/8ce5867a-8120-4db3-b936-c08f934cfd5a)

3.
en el punto 17 no sé cómo lograr ese -1 que debería ser el equivalente a : '', segun tengo entendido el alfabeto ASCII solo utiliza numeros positivos, o no?
![image](https://github.com/user-attachments/assets/6d5de32b-e70b-4a93-9773-93efbfbec19f)

Gracias de antemano!

**Comment by keljozap** [comment]
Hola @AlejandroEnciso7 

1. Punto 8. Estas haciendo un formateo incorrecto, el ejercicio te está pidiendo una fecha y tu estás entregando un varchar (string). Tal vez esta documentación te ayude https://duckdb.org/docs/sql/functions/date
2. Punto 15. Nuevamente estas entregando el resultado como tipo string (varchar) y el ejercicio tiene en cuenta el tipo que entregas, en este caso te pide entregar un DATE
3. Punto 13. Igual que los dos anteriores.
4. Punto 17. Te están pidiendo devolver caracteres unicode, no ASCII, son diferentes. Tal vez esto te ayude https://symbl.cc/en/unicode-table/

Saludos!

**Comment by AlejandroEnciso7** [comment]
los puntos 13-14 y 15 me siguen dando error incluso cuanod utilice un DESCRIBE antes para asegurarme de que efectivamente se estaban trabajando y resultando como DATE , los otros puntos si me ayudo lo que me dijiste muchas gracias 😄
