### ISSUE TITLE
Taller E28_P20 punto 15

### ISSUE THREAD

**Issue by andresgonzalezrpo** [codingupmyfuture/bootcampduckdb#38]
Punto 15. ¡Tu misión es clara! Encuentra aquellos colegios donde haya habido casos de COVID ....

No veo relación entre colegios y casos de covid.
Mi pregunta es: ¿Quisiera saber si estoy haciendo mal mi razonamiento o quizás hay un error ya sea en el enunciado o en la base de datos?
@luisvasv-teck 
Gracias.

**Comment by luisvasv-teck** [comment]
Recuerda que el soporte es comunitario,  es imposible que de mi lado u otra persona te dé soporte si no entregas contexto del taller, punto y dudas documentadas. Por favor proporciona más información para poder ayudarte en tu duda.

**Comment by emmanuelcasti1** [comment]
> Punto 15. ¡Tu misión es clara! Encuentra aquellos colegios donde haya habido casos de COVID ....
> 
> No veo relación entre colegios y casos de covid. Mi pregunta es: ¿Quisiera saber si estoy haciendo mal mi razonamiento o quizás hay un error ya sea en el enunciado o en la base de datos? @luisvasv-teck Gracias.

Compa, ¿obtuvo alguna solución? tambien tengo la misma situación.

**Comment by sarapalacio010** [comment]
![Captura de pantalla 2024-11-03 163727](https://github.com/user-attachments/assets/66e51312-72c9-436d-b344-3ae376d903f8)


Para complementar el issue / adjunto la imagen del taller que solo muestra un unico atributo nombre_colegio; sin embargo los datos corresponden a nombre de hospitales.

La respuesta esperada debería ser de acuerdo al enuncidado : la respuesta del ejercicio 15 debería ser **colegios** donde haya habido casos de COVID y **hospitales** que hayan recibido recursos para la batalla.

**Comment by andresgonzalezrpo** [comment]
@luisvasv-teck creo que el issue quedó etiquetado como invalido pero ya se ha documentado un poco más si de pronto se puede revisar.
Gracias
