### ISSUE TITLE
error boot calicación

### ISSUE THREAD

**Issue by Eduard-Atehortua** [codingupmyfuture/bootcampduckdb#39]
En Varios ejercicios me dice que fallé y cuando voy a la explicación, claramente esta correcto el ejercicio. Parece no reconocer el nombre de las columnas siquiera. Es algo frustrante

**Comment by luisvasv-teck** [comment]
Para poder ayudarte, es importante que pongas el caso y determinar si la causa es de nuestro lado, o el tuyo, indicar más información para poder validar.

**Comment by keljozap** [comment]
Hola @Eduard-Atehortua puedes por favor indicarnos que notebook, que ejercicios y que te muestra el resultado para poder ayudarte? Requerimos esta información ya que la descripción del issue no nos dice nada. Si deseas puedes adjuntar los casos en los que presentas el error.

Saludos!

**Comment by Eduard-Atehortua** [comment]
Hola Luis. Los posibles errores que encuentro son acerca del taller DUCKDB_SQLFECATE_E20_P10. Estos concretamente en n los puntos 12, 16,18,19. En algunos casos presenta resultados que no son los enviados por mi. 

https://drive.google.com/drive/folders/107zxhinD5WGxctMbtCUPglwXwWvmoMK5?usp=drive_link

**Comment by Eduard-Atehortua** [comment]
Posiblemente sea mejor volver a enviarlo ya que veo que parece han estado mejorado el funcionamiento del bot, según lo que leo. Muchas gracias.

**Comment by Eduard-Atehortua** [comment]
> Para poder ayudarte, es importante que pongas el caso y determinar si la causa es de nuestro lado, o el tuyo, indicar más información para poder validar.

Hola Luis. Los posibles errores que encuentro son acerca del taller DUCKDB_SQLFECATE_E20_P10. Estos concretamente en n los puntos 12, 16,18,19. En algunos casos presenta resultados que no son los enviados por mi.

https://drive.google.com/drive/folders/107zxhinD5WGxctMbtCUPglwXwWvmoMK5?usp=drive_link

Trataré de enviarlo otra vez ya me veo que han hecho mejoras en el bot, según leo.
