### ISSUE TITLE
SQLSELECT E28 P20, punto 16

### ISSUE THREAD

**Issue by Jenn0407** [codingupmyfuture/bootcampduckdb#40]
Buenas noches,
Tengo una duda en cuanto a la información pedida en este pnto

Punto 16. Combina los datos de comparendos que ya han sido pagados y los accidentes graves (MUERTO) que han ocurrido en la misma ciudad, (Según mi análisis, noto que en ninguna de las tablas requerida para el ejercicio haya un atributo llamado 'Ciudad' ni tampoco comparten relación con la tabla llamada demografia.tipo_ciudad) entonces a la hora de querer consultar por los accidentes graves que han ocurrido en la misma ciudad (No encuentro la manera de obtener ese dato), ademas, pide: Muestra el número de placa o el número del accidente y si es un "Comparendo" o un "Accidente", en esta última parte tampoco encuentro la opción 'Accidente' entre los datos que tienen las tablas. Muestro a continuación las opciones que me arroja 'transito.tipo_gravedad_accidente'  ni 'transito.tipo_clase_accidente'
![image](https://github.com/user-attachments/assets/73b29985-8ada-4117-b78b-9809d1cd4369)
![image](https://github.com/user-attachments/assets/7c064617-ab67-44e2-a4d4-44792b4ac8d9)

Les agradezco mucho si me pueden corregir en algo que estoy obviando, o tambien sino estoy haciendo bien el análisis. 

Pd: En el modelo relacional, la parte de los accidentes, arroja error al momento de la busqueda por 'educacion.accidentes'  por lo que comparto con ustedes la manera en que me trajo los datos de esa tabla: 'transito.accidentes', y la parte de 'turismo' en las otras dos tablas debe reemplazarse por 'transito', para que traiga la información.
![image](https://github.com/user-attachments/assets/2bda46ec-2936-413c-808f-5bcbc548f66d)

**Comment by keljozap** [comment]
Hola @Jenn0407 espero te encuentres bien.

Revisando el punto 16 del notebook al que te refieres, encontré lo siguiente:

1. El enunciado efectivamente indica que los resultados deben ser en la misma ciudad pero como tu lo has indicado más arriba, no existe el campo ciudad en ninguna de las tablas relaciondas a transito por lo que este es un dato cáscara.
2. El ejercicio te está pidiendo que combines los datos de los comparendos ya pagados (tabla comparendos que no adjuntaste) y los accidentes graves (es decir, cuya gravedad es 'Muerto'). El ejercicio dice combinar, y la descripción del ejercicio ya te indica las operaciones a las que se está haciendo referencia SELECT - WHERE - UNION.
3. Debes encontrar la condición del where que ya estableciste no es ciudad.
4. Debes realizar una subconsulta para llegar al resultado final.

Espero te sirva de ayuda.

Saludos!

**Comment by Jenn0407** [comment]
Agradezco mucho tu ayuda, feliz tarde .
