### ISSUE TITLE
Taller E28_20 puntos 12,14,16,18,19,20,25 posibles errores en calificación del bot

### ISSUE THREAD

**Issue by andresgonzalezrpo** [codingupmyfuture/bootcampduckdb#41]
Punto 12
En la revisión el boot parece que está calificando algún tipo de ordenamiento que no logró identificar en los resultados de la columna entidad, sin embargo en el enunciado no se pide ningún tipo de ordenamiento.
Revisar porfa si hay algún tipo de error.
esto fue lo que recibí en los resultados
At positional index 0, first diff: Registeel != Latios
gracias.

Ejercicio 14: ¡Ciudades con Doble Desafío!
Según la revisión dice que la respuesta son solo estas ciudades

![Imagen1](https://github.com/user-attachments/assets/041648a0-f5e7-41a4-9876-ca110dd9a11b)

Pero haciendo una revisión yo veo muchas más, nuevamente puedo estar equivocado en mi razonamiento pero me gustaría si lo pueden revisar.
también dice que ordenar el resultado por población de forma DESC pero según la respuesta del control no lo veo ordenado como se pide
gracias

Punto 16
El bot está calificando algún tipo de ordenamiento que no es pedido en el enunciado y tampoco logro identificar en la respuesta obtenida en los resultados.

Punto 18
Me dice que la respuesta tiene una longitud diferente pero realmente no logro identificar el error, la consulta me parece algo sencillo entonces si se puede revisar sería excelente

Punto 19
El enunciado pide llamar la columna 'comuna' y en el control lo piden como 'ciudad'.
igualmente lo cambié a 'ciudad' para la segunda revisión

Punto 20
Nuevamente está calificando algún tipo de ordenamiento que no se pide en el enunciado y que no logro deducir según la respuesta del bot

Punto 25
El bot está calificando algún tipo de ordenamiento que no es pedido en el enunciado y tampoco logro identificar en la respuesta obtenida en los resultado

**Comment by andresgonzalezrpo** [comment]
**Punto 13:** Parece que en este punto también está calificando algún tipo de ordenamiento que no es pedido en el enunciado. No lo había reportado por que en mi segundo intento lo ordené para que quedara como estaba en el control pero en la segunda respuesta llegó en diferente orden nuevamente por parte del control. Además el enunciado sugiere usar UNION sin embargo, no lo encuentro necesario. nuevamente puedo estar equivocado pero dejo el comentario para revisión. 

![Imagen1](https://github.com/user-attachments/assets/cf446cd2-1a1c-45bb-b736-2fcb8bfbff24)

dejo el enunciado si se requiere más contexto.
DESCRIPCIÓN: SELECT - UNION
Ejercicio 13: Batalla épica: Pokémon con ataques y defensas fuera de lo común

Crea una consulta que liste los Pokémon cuyos ataques o defensas son mayores a 200. Selecciona el nombre, ataque y defensa de los pokemones.

Tips: Usa WHERE ataque > 200 OR defensa > 200 para cada consulta y luego combina ambas usando UNION. ¡Recuerda, el poder está en la diversidad de los Pokémon!
Recuerde que debe usar SELECT

**Punto 18**. Revisando nuevamente el punto, dejo el enunciado

ID: SQLSELECT-18
DESCRIPCIÓN: SELECT - UNION ALL
Ejercicio 18: Colegios por áreas y tipos de género: ¡sin filtro!

Necesitamos obtener una lista de colegios, tanto por su área geográfica (rural o urbana) como por el tipo de género de los estudiantes (mixto o solo un género). Queremos ver todos los datos, sin eliminar duplicados. Extrae el nombre y tipo de area de todos los colegios categorizados por dichos factores, sin eliminar ninguna repetición.

según entiendo la consulta no requiere filtro(WHERE) por que pide todos los datos, incluso dice sin filtro:
area: Rural o urbano ( que son las únicas 2 que existen)
genero: Mixto, masculino o femenino
igualmente voy a dejar mi query por si alguien me puede dejar alguna sugerencia.

SELECT nombre_colegio, id_tipo_area_colegio FROM demografia.colegios
UNION ALL
SELECT nombre_colegio, id_tipo_genero_colegio FROM demografia.colegios

Muchas gracias por tomarse el tiempo de leer cada uno de los comentarios, quedo atento para volver a enviar mis respuestas.

**Comment by keljozap** [comment]
Hola @andresgonzalezrpo

Punto 13: 
El ejercicio 13 tiene como objetivo evaluar lo aprendido en el curso, y en este caso la sentencia UNION, tal vez no lo veas necesario pero es el objetivo del punto. Relacionado a este mimo punto, el ejercicio no te está pidiendo un ordenamiento como tal, los valores adjuntados en el ejemplo del resultado pueden variar y es este motivo por lo que el punto se te calificó como bueno. Si bien tu query es distinto tu resultado es correcto, recuerda que en este curso estamos calificando que hayan **interiorizado los fundamentos de SQL**, **no estamos pretendiendo que mecanicen**.

Punto 18. 
ecuerda que en este curso estamos calificando que hayan **interiorizado los fundamentos de SQL**, **no estamos pretendiendo que mecanicen**. En este caso el enunciado está pidiendote que tengas en cuenta ciertos aspectos de los colegios, tal vez con esta BD tu razonamiento sea correcto, pero, que pasaría si agregamos otro tipo de area u otro genero? tu query no traería los resultados correctos. **La idea de un query es dar respuesta a una pregunta, no basarse en los datos para construir el query.**

Saludos!

**Comment by edallanpoe** [comment]
> Hola @andresgonzalezrpo
> 
> Punto 13: El ejercicio 13 tiene como objetivo evaluar lo aprendido en el curso, y en este caso la sentencia UNION, tal vez no lo veas necesario pero es el objetivo del punto. Relacionado a este mimo punto, el ejercicio no te está pidiendo un ordenamiento como tal, los valores adjuntados en el ejemplo del resultado pueden variar y es este motivo por lo que el punto se te calificó como bueno. Si bien tu query es distinto tu resultado es correcto, recuerda que en este curso estamos calificando que hayan **interiorizado los fundamentos de SQL**, **no estamos pretendiendo que mecanicen**.
> 
> Punto 18. ecuerda que en este curso estamos calificando que hayan **interiorizado los fundamentos de SQL**, **no estamos pretendiendo que mecanicen**. En este caso el enunciado está pidiendote que tengas en cuenta ciertos aspectos de los colegios, tal vez con esta BD tu razonamiento sea correcto, pero, que pasaría si agregamos otro tipo de area u otro genero? tu query no traería los resultados correctos. **La idea de un query es dar respuesta a una pregunta, no basarse en los datos para construir el query.**
> 
> Saludos!

tener que en cuenta que sí bien no se solicita explicitamente agregar filtros al query, si se está especificando de manera implicita los valores por los cuales se debe acotar los datos a consultar.
![Screenshot 2024-11-08 at 3 51 14 PM](https://github.com/user-attachments/assets/bd2dc9cb-4ad6-4b41-b386-668224e7d21b)

**Comment by andresgonzalezrpo** [comment]
punto 14: Hola, sigo teniendo inconvenientes con el , sigo obteniendo muchas mas ciudad con doble desafío de covid y suicidio, no sé si quizás estoy haciendo una interpretación errada del enunciado. Además veo que el ejercicio pide ordenar de forma DESC en cuanto al número de población y en el control aparece Rionegro primero que Medellín.

![Imagen2](https://github.com/user-attachments/assets/4805f379-ca11-4635-a886-33ec057bdb5a)

De pronto alguno de los compañeros tiene este punto bueno?
Punto 15: había mencionado en otro issue que en la base de datos los colegios no están relacionados con el covid, pero aún no recibo respuesta.

Punto 18: ya puse el filtro que me pediste @keljozap pero sigo obteniendo el mismo error.
Gracias por tu tiempo

**Comment by keljozap** [comment]
Hola @andresgonzalezrpo.
Punto 14. Sino te molesta podrías adjuntar la consulta para mirar que error podrías tener?
Punto 15. Para resolver este punto deberás usar una unión entre la tabla demografía colegios y la tabla infraestructura hospitales teniendo en cuenta las condiciones que el enunciado te indica, recuerda que es un ejercicio de UNION.
Punto 18. Puedes poner tu consulta aquí para mirar.

Saludos!

**Comment by andresgonzalezrpo** [comment]
Punto 14: query
SELECT codigo_ciudad, nombre_ciudad FROM (
        SELECT DISTINCT codigo_ciudad, nombre_ciudad, nro_poblacion FROM demografia.tipo_ciudad
        WHERE id_ciudad IN (
          SELECT id_ciudad FROM demografia.suicidios WHERE nro_casos > 0
          )

        UNION ALL

        SELECT DISTINCT codigo_ciudad, nombre_ciudad, nro_poblacion FROM demografia.tipo_ciudad
        WHERE id_ciudad IN (
          SELECT id_ciudad FROM demografia.covid
          )
) AS t
GROUP BY 1,2,nro_poblacion
HAVING COUNT(codigo_ciudad)>1
ORDER BY t.nro_poblacion DESC;

Punto 18 
SELECT nombre_colegio, id_tipo_area_colegio FROM demografia.colegios
WHERE id_tipo_area_colegio IN (
  SELECT id_tipo_area_colegio FROM demografia.tipo_area_colegio
  WHERE nombre_area = 'RURAL' OR nombre_area = 'URBANA'
)
UNION ALL
SELECT nombre_colegio, id_tipo_genero_colegio FROM demografia.colegios
WHERE id_tipo_genero_colegio IN (
  SELECT id_tipo_genero_colegio FROM demografia.tipo_genero_colegio
  WHERE nombre_genero = 'MIXTO' OR nombre_genero = 'FEMENINO'
  OR nombre_genero = 'MASCULINO'
)

**Comment by keljozap** [comment]
Hola @andresgonzalezrpo 

Punto 14. Estás usando una subconsulta donde no es necesario. La subconsulta debería ir en el WHERE de la consulta principal, y la consulta principal es la que debe tener el DISTINCT no las subconsultas. No puedo revelarte más pero si está incorrecto el planteamiento del query.

Punto 18. En este punto estás teniendo las condiciones como te lo indicamos anteriormente pero, incorrectamente, no necesitas una subconsulta en este ejercicio. Si quieres filtrar por al area rural puedes hacerlo con el campo id_tipo_area_colegio. Si filtras con el campo id_tipo_area_colegio de esta forma WHERE id_tipo_area_colegio IN (1, 2) -- 1: Rural, 2: Urbana estás teniendo en cuenta el area rural y urbana sin tener en cuenta el nombre del area.

Espero estas respuestas te sirvan.

Saludos!

**Comment by andresgonzalezrpo** [comment]
@keljozap 
Punto 14  Te quiero explicar mi query por que sé que a veces es difícil entender la lógica de otro, más que por la nota es por que no me gusta quedarme con la duda de lo que hice mal. 
El punto pide en pocas palabras mostrar las ciudad que han tenido casos de covid y suicidios "Tu misión es identificar las ciudades que han registrado casos de suicidios y contagios de COVID."
y dan un TIP "Para esto, debes realizar dos consultas separadas para cada tipo de evento y luego combinar los resultados. "
la lógica que apliqué con este TIP es:
1. revise las ciudades que han tenido por lo menos 1 suicidio ( acá uso el DISTINCT porque solo quiero traer una)
 SELECT DISTINCT codigo_ciudad, nombre_ciudad, nro_poblacion FROM demografia.tipo_ciudad
        WHERE id_ciudad IN (
          SELECT id_ciudad FROM demografia.suicidios WHERE nro_casos > 0
          )
2. revise las ciudades que han tenido por lo menos 1 caso de covid ( acá uso el DISTINCT porque solo quiero traer una).
SELECT DISTINCT codigo_ciudad, nombre_ciudad, nro_poblacion FROM demografia.tipo_ciudad
        WHERE id_ciudad IN (
          SELECT id_ciudad FROM demografia.covid
          )
3. luego hago un UNION ALL para juntar los resultados, pero que no me borre las ciudades repetidas por que lo que quiero es encontrar aquellas ciudades que aparecen 2 veces. Si aparece 2 veces, como me estoy asegurando que solo aparezca una vez con covid y una vez con suicidios, es por que han tenido caso de covid y suicidio, para esto uso el HAVING COUNT(codigo_ciudad)>1
6. ordeno por población DESC como lo pide el enunciado, que acá veo que el control tiene un problema ya que muestra primero Rionegro que Medellín por ejemplo.

Punto 18 ya lo cambié, aunque eso no cambia la longitud de la respuesta que es lo que me está indicando el bot:
"Ejercicio no superado. Puntuación obtenida: 0.0% Puntuación mínima requerida: 75.0%
Debido a: La solución no superó la prueba: La respuesta del estudiante tiene una longitud
distinta a la respuesta del control."
SELECT nombre_colegio, id_tipo_area_colegio FROM demografia.colegios
WHERE id_tipo_area_colegio IN (1,2)
UNION ALL
SELECT nombre_colegio, id_tipo_genero_colegio FROM demografia.colegios
WHERE id_tipo_genero_colegio IN (1,2,3);
