### ISSUE TITLE
La herramienta de calificación automática  no está calificando mis trabajos

### ISSUE THREAD

**Issue by malalalalala** [codingupmyfuture/bootcampduckdb#42]
Buena stardes, puse otro ticket que fue cerrado en el cual explica que no estoy enviando los talleres en forma adecuada. Sin embargo, los he enviado siguiendo todas las especificaciones. Creo que pued etener que ver que lo envío desde outlook pero no estoy segura, hay forma de enviarlos desde otro correo?

**Comment by malalalalala** [comment]
![Capture3 code](https://github.com/user-attachments/assets/d20ee2a0-dd06-48f3-85ac-7460ebe26b8b)
![Capture2 code](https://github.com/user-attachments/assets/8eaed910-5c62-49a0-9241-ba644d437597)
![Capture1 code](https://github.com/user-attachments/assets/44c245ff-45b7-499f-9aee-8028fc732a0d)

**Comment by luisvasv-teck** [comment]
Por favor mirar el issue #34 

Tampoco archivos compartidos:

![image](https://github.com/user-attachments/assets/567daf87-e305-478d-b1d9-4a2367f0e48c)

Por favor seguir la documentación, gracias.
