### ISSUE TITLE
Taller DUCKDB_SQLBBDDFIS_E22_P10: Posibles errores de calificación en ejercicios 9, 10, 12

### ISSUE THREAD

**Issue by afflorezc** [codingupmyfuture/bootcampduckdb#43]
En estos ejercicios estoy obteniendo los resultados esperados y manejando los casteos requeridos (DECIMAL en puntos 9 y 10 y DOUBLE) en 12. En el taller hay otros ejercicios donde se deben ejecutar consultas SQL con este tipo de casteo y no generan este mismo error. El error que se muestra para estos ejercicios es sobre tipo erróneo o no coincidente: 

Ejercicio 9.
![image](https://github.com/user-attachments/assets/75614f2d-b59b-42ed-a766-a6e365fa0385)
![image](https://github.com/user-attachments/assets/343d9898-d560-4a20-8c3e-21716a76ebd7)

Ejercicio 10.
![image](https://github.com/user-attachments/assets/835cf828-270e-4dae-8b7c-8e573f872b36)
![image](https://github.com/user-attachments/assets/80ebfdc5-91f3-4826-bf21-8c3a624beca2)

Ejercicio 12.
![image](https://github.com/user-attachments/assets/7e5eca05-a2ba-4dc6-9e1f-9de62fb0322c)
![image](https://github.com/user-attachments/assets/89957a3e-976f-41c4-9512-36e91b5ee6bd)

**Comment by JikaS14** [comment]
los puntos 9 y 10 como que ya califica bien, pues tengo los mismos resultados. en el caso del 12 si tengo el mismo error:
![imagen](https://github.com/user-attachments/assets/4e6d0639-03bf-4fe8-8265-de5947360d9d)
![imagen](https://github.com/user-attachments/assets/ee6ffdc9-39b6-401d-a85d-44280a61117b)

**Comment by keljozap** [comment]
Hola @afflorezc.

Punto 9. El enunciado te está pidiendo que solo hagas una división, para lo cual no es necesario un casteo ni una subconsulta. Aunque el calificador lo haya calificado correctamente tu query no es el más optimo.
Punto 10. Nuevamente no era necesaria la subconsulta y agregaste escala y precisión donde no era requerido. Aunque el calificador lo haya calificado correctamente tu query no es el más optimo.
Punto 12. Tienes un casteo donde no es requerido y una subconsulta que no es necesaria.

Saludos!
