### ISSUE TITLE
Pregunta 2, Taller DUCKDB_SQLALMS_E18_P20

### ISSUE THREAD

**Issue by Jenn0407** [codingupmyfuture/bootcampduckdb#44]
Buenas noches, 

Quisiera saber si alguno esta presentando el mismo inconveniente con la calificación del punto 2 del taller DUCKDB_SQLALMS_E18_P20, ya que en las calificaciones del Bot, este punto lo calificó con 0, pero veo que lo tengo de acuerdo a lo pedido por el control.
Este es mi resultado: 
![image](https://github.com/user-attachments/assets/85592a0a-0c63-4c85-80ad-52bc9dca2442)
Este es el resultado del Bot:
![image](https://github.com/user-attachments/assets/212c7397-fca9-41fd-879e-76bee2abb477)
No sé por qué me lo esta marcando en resultados estudiante con las inciales en minúscula, cuando en mi notebook lo tengo de acuerdo al resultado del control (En mayúsculas las iniciales)

Agradezco mucho la ayuda que me puedan brindar, feliz noche!

**Comment by AlejandroEnciso7** [comment]
Sí a mí también me está ocurriendo lo mismo, como si el calificador forzara un LOWER() sobre los resultados.

**Comment by luisvasv-teck** [comment]
Mira muy bien lo que espera el control, y lo que estás entregando, quizás notes la posible diferencia

**Comment by Jenn0407** [comment]
@luisvasv-teck la respuesta de mi notebook, es igual a la que pide el control, pero no sé por qué en la entrega lo esta tomando con minusculas que no he puesto.

**Comment by andresgonzalezrpo** [comment]
@Jenn0407 tuviste respuesta a este error?, me pasa exactamente lo mismo.

**Comment by Jenn0407** [comment]
Hola @andresgonzalezrpo, no.
