### ISSUE TITLE
Pregunta 10 taller E18_P20

### ISSUE THREAD

**Issue by AlejandroEnciso7** [codingupmyfuture/bootcampduckdb#45]
En mi compilador y en Dbeaver también realice la prueba y en ambos me da el resultado que espera el calificador:
![image](https://github.com/user-attachments/assets/7c0a0142-946e-4660-be59-805cd32cca95)

![image](https://github.com/user-attachments/assets/25218924-4b3a-4204-a324-728d102fa6b2)

![image](https://github.com/user-attachments/assets/4155e533-bb19-4ab9-9a57-6dd172ecb32c)

Sin embargo, no entiendo el error que me arroja, hasta donde creo entender es un error del calificador como tal, pues dice que el problema es desde esta ruta "File "/Users/lvasq/repositories/personal/evaluator/evaluator/src/qualifier/exercise/sql.py", que seria el computador del profesor?

Adjunto también el error completo por si alguien más le ha aparecido:
![image](https://github.com/user-attachments/assets/194c0813-8c24-4621-b89b-ec94a684c1b4)

Gracias!

**Comment by keljozap** [comment]
Hola @AlejandroEnciso7.

Tienes razón, el calificador presenta un error en este punto, trabajaremos en el fix y te lo haremos saber del arreglo una vez este listo a través de los canales de comunicación.

Muchas gracias por este aporte!

Saludos!

**Comment by codingupmyfuture** [comment]
El ajuste fue realizado, en los próximos envíos no debe de pasar
