### ISSUE TITLE
Problemas con evaluación de talleres

### ISSUE THREAD

**Issue by LeonZapata18** [codingupmyfuture/bootcampduckdb#46]
Buenos días me dirijo a ustedes para solicitarles muy amablemente ayuda o soporte, ya que el martes 29 de octubre envié varios talleres para revisión y no he recibido ningún tipo de retroalimentación.

El día de ayer (jueves 31 de octubre), envié nuevamente uno de estos talleres, descargando nuevamente el correspondiente notebook y realizando el taller desde cero, considerando la posibilidad de que en algún momento pude haber alterado la integridad de los notebook's anteriormente enviados. Aún sigo sin recibir retroalimentación del segundo intento de evaluación.

Adjunto los pasos seguidos para el envío de las tareas y "evidencia" de envío del último taller.

![pasos_entrega](https://github.com/user-attachments/assets/c7797639-4af0-4f05-ad21-871b4ce3e04f)

![entrega](https://github.com/user-attachments/assets/f44dc42b-2b27-48ef-a954-618d5833ade8)

Quedo atento a sus observaciones y sugerencias.

Feliz día.

**Comment by luisvasv-teck** [comment]
De que correo estás enviando la información, o con que nombre, porque así es complicado

**Comment by LeonZapata18** [comment]
Buenos días
El correo usado es:

leon.zapata1802@gmail.com

**Comment by LeonZapata18** [comment]
Para la solución de este problema se solicitó cambio de correo para la entrega de las tareas, una vez hecho esto, las entregas realizadas a través del nuevo correo recibieron retroalimentación.
