### ISSUE TITLE
E21_P20 punto 1, 5, 19, 21

### ISSUE THREAD

**Issue by andresgonzalezrpo** [codingupmyfuture/bootcampduckdb#47]
Buenos días,
En el punto 1. debemos mostrar los 10 vehículos con más comparendos en su historial ordenado por comparendos DESC.
La calificación anterior me lo había calificado bien y en la última me llegó con un error, el cambio fue en el último dato. Adjunto imagen.

![Problemas](https://github.com/user-attachments/assets/70696438-b269-4063-948e-05602b03b079)

Se puede ver como el control en la imagen de la izquierda en el ultimo dato trae un valor diferente al de la imagen de la derecha.
esto es debido a que las 2 placas tienen la misma cantidad de comparendos y la placa que muestra al final debe ser aleatorio.
Es muy probable que al volver a enviarlo a calificación dé un resultado positivo cuando coincida pero dejo el comentario por si se puede eliminar la parte aleatoria.

Punto 5, 19 y 20 tienen el siguiente inconviente.
El alias de las 2 columnas que se muestran en el control son iguales. voy a adjuntar un ejemplo

![Imagen1](https://github.com/user-attachments/assets/e009302f-a9c2-4f3d-abe9-b1ffe96d48e6)

las 2 columnas se llaman id_ciudad. 

En las primeras calificaciones las deje con el mismo nombre y el control arroja el siguiente error
![Imagen2](https://github.com/user-attachments/assets/9fe22864-1d55-4548-bb0e-119776e83fe0)

En lo que estuve buscando el error es debido a que las dos columnas se llaman iguales.

En las siguientes entregas cambié el nombre de las columnas y ya no arroja el error pero no pasa el ejercicio debido al nombre de las columnas. Adjunto el ultimo resultado.

![Imagen3](https://github.com/user-attachments/assets/50542574-9551-4ab1-8824-f03afff30fe5)

no voy a subir las imágenes del punto 19 y 21 por que es exactamente lo mismo.
¿Que me pueden recomendar o se debe hacer algún ajuste por parte del bot?
Gracias.

**Comment by Dhmthe** [comment]
Me pasa exactamente lo mismo, no he podido dar con la solución, espero que @luisvasv-teck responda o alguien que ayude!

**Comment by keljozap** [comment]
Hola @andresgonzalezrpo y @Dhmthe.

Punto 1. Compañero @andresgonzalezrpo revisando el punto 1 del notebook SQLJOIN que nos adjuntas, tu consulta no tiene JOIN cuando el objetivo del ejercicio es usar JOIN ya que el punto requiere crear una sentencia GROUP BY por el número de placa desde la tabla vehiculos, NO desde la tabla comparendos. _El ejercicio especificamente cita "Tip: GROUP BY es como el detective que agrupa todas las pistas (en este caso, las placas de los vehículos) para que luego tú puedas contar cuántas veces han sido atrapados."_

Punto 5. Tienes razón, el ejercicio está mal formulado, vamos a anular este ejercicio. Cada nombre de columna debería ser único dentro de su mismo contexto.
Punto 19. Tienes razón, el ejercicio está mal formulado, vamos a anular este ejercicio. Cada nombre de columna debería ser único dentro de su mismo contexto.
Punto 21. Tienes razón, el ejercicio está mal formulado, vamos a anular este ejercicio. Cada nombre de columna debería ser único dentro de su mismo contexto.

Saludos!

**Comment by ChristYela** [comment]
Sigue dando errores de esos ejercicios por los nombres de columnas en esos numerales

**Comment by dcanosu** [comment]
Cordial saludo, 
En el punto 1 también estoy obteniendo el mismo resultado en el numero 9 no queda la placa ARP409 si no la placa RIG95B por lo cual el bot me lo devuelve incorrecto
<img width="433" alt="image" src="https://github.com/user-attachments/assets/28416275-c5cc-4917-bba5-ebb91b261a04">

<img width="375" alt="image" src="https://github.com/user-attachments/assets/059f6a47-8541-4138-8988-924d1cbf04fb">

**Comment by dcanosu** [comment]
En el punto 5, estoy obteniendo respuesta del bot, me indica que se espera una longitud diferente pero el ejercicio indica limit 4 al igual que el nombre aparece que debe de ser igual pero no lo permite.

<img width="393" alt="image" src="https://github.com/user-attachments/assets/02c5aa5f-1f36-4234-b5c2-cd2060241e51">

**Comment by ChristYela** [comment]
> Cordial saludo, 
> En el punto 1 también estoy obteniendo el mismo resultado en el numero 9 no queda la placa ARP409 si no la placa RIG95B por lo cual el bot me lo devuelve incorrecto
> <img width="433" alt="image" src="https://github.com/user-attachments/assets/28416275-c5cc-4917-bba5-ebb91b261a04">
> 
> <img width="375" alt="image" src="https://github.com/user-attachments/assets/059f6a47-8541-4138-8988-924d1cbf04fb">
> 
> 
A mi en un intento me lo tomó bueno y en otro intento me lo tomó malo, sin haber hecho nada de cambios en el código

**Comment by ChristYela** [comment]
En el punto (5) también tendría que considerar los valores Null o NaN pues algunas columnas tienen esos valores

**Comment by andresgonzalezrpo** [comment]
@dcanosu en el punto 1 lo ordené por cantidad de comparendos DESC, Y después por placa ASC  y pasó, aunque no debería por que no se pide el orden, pero así me pasó por si te sirve

**Comment by codingupmyfuture** [comment]
Los ejercicios fueron removidos. Para poder enviar sus trabajos, deben eliminar el ejercicio  5, 19 y 21, tanto la documentación como la fila donde está en `%%sql`
