### ISSUE TITLE
E21_P20 punto 14

### ISSUE THREAD

**Issue by Cris-Cod** [codingupmyfuture/bootcampduckdb#48]
Cordial Saludo
En el punto 14 del taller en donde se reporta  el desempeño promedio de los estudiantes de los colegios en el  examen del ifces se debe mostrar el nombre de la institución y el promedio de las calificaciones por materia.
El Bot reporta que la longitud es distinta a la del control pero al revisar no encuentro la diferencia

![image](https://github.com/user-attachments/assets/16cb7089-1607-488f-a8d2-b2fd8e74085f)

![image](https://github.com/user-attachments/assets/604217b4-a017-421a-acb3-08f0d7118367)

**Comment by Brahian2016** [comment]
Fijate el registro 8, el control arroja unos nan que tu no tienes. Ahí ya hay una diferencia en el resultado
