### ISSUE TITLE
Error en el modelo de datos

### ISSUE THREAD

**Issue by Brahian2016** [codingupmyfuture/bootcampduckdb#49]
Al revisar el modelo relacional mientras realizaba uno de los ejercicios, encontré un error en la estructura de esquemas. En la sección correspondiente a "accidentes", el modelo actual indica que:

- La tabla **accidentes** se encuentra en el esquema **educacion**.
- Las tablas **tipo_clase_accidente** y **tipo_gravedad_accidente** pertenecen al esquema **turismo**.
- 
Sin embargo, esto no es correcto. Las tres tablas (accidentes, tipo_clase_accidente y tipo_gravedad_accidente) realmente se encuentran  en el esquema **transito**.

![image](https://github.com/user-attachments/assets/f689da0c-1032-4ede-9d9b-33e90479d33b)

![image](https://github.com/user-attachments/assets/074daddc-8976-4af4-8e5c-11e22ac27ac0)

**Comment by luisvasv-teck** [comment]
Muchas gracias, por el reporte. Actualizaré los esquemas en el diagrama.

**Comment by codingupmyfuture** [comment]
issue resuelto: https://github.com/codingupmyfuture/bootcampduckdb/tree/main/contenido.curso/000.recursos/db
