### ISSUE TITLE
Duda con resultado del punto 12, E_22_P10

### ISSUE THREAD

**Issue by JessiGM** [codingupmyfuture/bootcampduckdb#51]
Buenos días compañeros tengo una duda, no se si alguien más tuvo el incoveniente:
En el ejercicio #12 de este taller tengo lo siguiente:

![Captura de pantalla 2024-11-07 113010](https://github.com/user-attachments/assets/bbaa2905-6779-4e0d-81ce-4f78900fe6f2)

dice que utilice tipo DOUBLE que es lo que hago, pero el bot me responde que no es float64.

Esto es lo que dice el bot:
Ejercicio no superado. Puntuación obtenida: 0.0% Puntuación mínima requerida: 75.0%
Debido a: La solución no superó la prueba: Attributes of DataFrame.iloc[:, 0] (column
name="perimetro") are different Attribute "dtype" are different [left]: object [right]: float64.

Si alguien me puede ayudar se lo agradezco  mucho!

**Comment by danielcardenasparra** [comment]
Hola quitale el CAST y el as a double  : 
SELECT
(2 * 3.1415 * 7.5) * 1.0 AS perimetro,
(3.1415 * 7.5 * 7.5) * 1.0 AS area;

**Comment by JessiGM** [comment]
Muchas gracias Daniel, ya lo intente pero tampoco da, igual genera error.

**Comment by danielcardenasparra** [comment]
Que raro a mi me lo paso como valido

**Comment by JessiGM** [comment]
Quien sabe que pasará

**Comment by danielcardenasparra** [comment]
Colocarias porfavor el erro que te sale en el pdf el que envia el osea comparando lo que da estudiante y control ?

**Comment by JessiGM** [comment]
Si claro, aquí está como lo había realizado anteriormente:
![image](https://github.com/user-attachments/assets/4aeb03e1-09b7-4b18-a5eb-cfe0ddd5f66e)
, después lo hice como me dijiste y sale igual con error, el mismo.

**Comment by JikaS14** [comment]
Tuve el mismo problema, y es el único punto que me falto de ese taller

**Comment by keljozap** [comment]
Hola @JessiGM, @JikaS14, @danielcardenasparra 

Punto 12. El ejercicio está pidiendo que se use el tipo de dato DOUBLE para la solución, y aunque el casteo es una solución correcta también lo es la que plantea @danielcardenasparra solo que ligeramente diferente.

Si estas usando DOUBLE el 2 también debería ir como DOUBLE, en ese caso, el 2 en la respuesta de @danielcardenasparra debería ser un 2.0. Por favor intentalo de esa forma y en cualquier caso postea aquí mismo si eso solucionó tu problema.

Saludos!
