### ISSUE TITLE
Duda con resultado del punto 21 E22_P10

### ISSUE THREAD

**Issue by JessiGM** [codingupmyfuture/bootcampduckdb#52]
Buenas tardes compañeros, alguien me puede ayudar con esto por favor?
En el punto #21 de este taller el bot me calfica con error según entiendo porque estoy poniendo "dentro del rango" y debe ser "Dentro del rango" es decir con mayúscula, pero en realidad lo tengo tal cual con mayúscula, de pronto a alguien más le pasó?

Adjunto evidencia.
![Captura de pantalla 2024-11-07 135707](https://github.com/user-attachments/assets/766502ee-cffe-43a0-9f39-636033cc5102)

Si alguien me puede ayudar se lo agradezco.

**Comment by juli-amezquita** [comment]
Hola @JessiGM, creo que lo que pide el bot es ponerlo en minúscula: 'dentro del rango' y 'fuera del rango'. Al menos a mi me lo calificó bien así la semana pasada, no sé si esto cambió. Espero te ayude.

**Comment by JessiGM** [comment]
Hola Juli, si muchas gracias, eso hice y si me sirvio.
