### ISSUE TITLE
DUCKDB_SQLALMS_E18_P20 - Pregunta 5 y 10

### ISSUE THREAD

**Issue by DanielaVL** [codingupmyfuture/bootcampduckdb#53]
Cordial saludo, no sé por qué me está marcando error en ambas preguntas si en mi mi notebook lo tengo de acuerdo al resultado del control. Agradezco mucho la ayuda que me puedan brindar.

Pregunta 5:
![image](https://github.com/user-attachments/assets/4d3133c0-4268-42fb-a9cd-53f4d61b6cef)

Pregunta 10:
![image](https://github.com/user-attachments/assets/1192bf96-4406-4537-a362-ae5796063fec)
![image](https://github.com/user-attachments/assets/2feb29a2-f51f-41dc-b109-c6bb9bfbfaca)

**Comment by JikaS14** [comment]
Bueno, a mi me paso lo siguiente en mi primer envío:

![Screenshot_20241107-203724_1.png](https://github.com/user-attachments/assets/551a6896-1455-4505-b53f-a99fc92bded7)

Y claro el error fue el paréntesis () así que cambie todo con corchetes [] y con eso  aprobé.

![Screenshot_20241107-203225_1.png](https://github.com/user-attachments/assets/d06698a3-f98f-4fad-a7af-7558a1b94edd)

En el segundo fallo si tuve el mismo problema y es el único punto que me falto por aprobar, me sale el siguiente mensaje:

![Screenshot_20241107-203419_1.png](https://github.com/user-attachments/assets/8f59385d-f05f-4943-917e-5fd3b4b1f94f)

A pesar que en el cuaderno funciona, en la respuesta del bot, aparece como que uno no hubiera respondido nada. Así que tengo el mismo problema. XD

**Comment by ChristYela** [comment]
@JikaS14 y esos parentesis donde iban? y ese cambio a corchetes . era en donde creaba la tabla temporal?

**Comment by JikaS14** [comment]
Yo tenia lo siguiente después del select array:

('pan mimbo' , 'panadería' ) 
Así con todos los demás productos y cerraba con otro paréntesis para la etiqueta "inventario" 

El cambio fue cambiar a corchetes 
['pan mimbo' , 'panaderia' ] 
Así con todas las parejas y al final también para la etiqueta.

**Comment by DanielaVL** [comment]
@JikaS14 Muchas gracias, eso que mencionaste me ayudó a organizar la pregunta 5.
La pregunta 10 si está como imposible, creo que muchos le hemos intentado de todas las maneras y no funciona, pareciera ser error del bot, esperemos que el profe nos pueda leer.

**Comment by keljozap** [comment]
Hola @DanielaVL, @JikaS14, @ChristYela

Punto 5. Parece que ya te ayudaron a resolverla, gracias a los compañeros.
Punto 10. Hay un problema con el calificador en este tipo de puntos y se va a lanzar un fix para resolver este problema. Por favor leer el issue #45 para mas indormación.

Saludos!

**Comment by keljozap** [comment]
Para el punto 5 pueden ir a revisar el issue #56 si quieren ver el resultado.

Saludos!

**Comment by DanielaVL** [comment]
@keljozap Muchas gracias por leernos y colaborarnos.

**Comment by ChristYela** [comment]
@keljozap Gracias por sus respuestas y por la referencia en mis issues. Feliz finde

**Comment by codingupmyfuture** [comment]
El ajuste fue realizado, en los próximos envíos no debe de pasar

**Comment by juli-amezquita** [comment]
Hola chicos, entiendo que hicieron un ajuste a la pregunta 10. Sin embargo, yo la hice utilizando MAP al principio de la consulta (ya que el ejercicio pide crear un MAP), y el bot me la calificó bien:

`SELECT MAP {'key1': 10, 
'key2:'...}`

Para resolver el ejercicio utilicé esta parte de la documentación: https://duckdb.org/docs/sql/data_types/map.html
Espero sea de ayuda.
