### ISSUE TITLE
Consulta del taller E_28_P20 - ejerciocio 26

### ISSUE THREAD

**Issue by bospina-lealco** [codingupmyfuture/bootcampduckdb#54]
En colab me muestra el resultado de esta manera 
![image](https://github.com/user-attachments/assets/949abde0-5b0b-4811-8060-a8b88b61bf7e)

pero en mi editor si lo muestra correctamente como debe de ser el ejerciocio 
![image](https://github.com/user-attachments/assets/f4249709-7d94-45b6-9b01-3685926b3330)

puede enviarlo sin temor a que me lo tome erroneo

**Comment by keljozap** [comment]
Hola @bospina-lealco 

La única manera de saberlo es intentarlo!. Recuerda que los ejercicios tienen la posibilidad de enviarse multiples veces hasta la fecha de cierre del curso. No puedo decir si tu query es adecuado o no, ya que al no haber enviado tu notebook no tengo forma de acceder a tu información.

Una vez lo hayas enviado y el calificador te haya dado respuesta, si te lo califica incorrectamente te pido que habrás otro issue explicando el error que te envió el calificador.

Saludos!
