### ISSUE TITLE
EJERCICIO - ID: SQLALMS-03

### ISSUE THREAD

**Issue by ChristYela** [codingupmyfuture/bootcampduckdb#55]
En el ejercicio EJERCICIO - ID: SQLALMS-03. tengo tanto en los valores esperados y mis valores : 

Esperado: 
![image](https://github.com/user-attachments/assets/63e9f7ca-c05d-4d82-a2d8-c31fa804afa2)

Mi resultado:
![image](https://github.com/user-attachments/assets/4f01ac03-ec9c-4de5-898e-6f9cb94e1bfa)

Reporte según el PDF: 
![image](https://github.com/user-attachments/assets/7dee20f0-f7c4-4926-9f85-a8a0963768f7)

Alguien podría explicar que pasó aquí?: 
![image](https://github.com/user-attachments/assets/b154e637-e9bb-4d03-a9a1-6f0c892074ec)

 Muchas gracias!

**Comment by ChristYela** [comment]
@luisvasv-teck Podrias validar esto cuando tenga tiempo si es tan amable, Gracias

**Comment by edallanpoe** [comment]
Hola @DanielaVL, agradecemos tu issue, sin embargo, despues de una revisión extensiva tanto del bot como los notebooks y correspondientes enunciados del punto 3 respectivamente, encontramos que el error se encuentra en la formulación del query:

En el Punto 3: Realizas un casteo a varchar, cuando lo que se solicita es un tipo timestamp/datetime.

Agradecemos tu dedicación a la clase.

Saludos cordiales.

**Comment by ChristYela** [comment]
@keljozap @edallanpoe Muchas gracias por sus respuestas, ya haciendo las correcciones necesarias en los ejercicios según feedback. feliz finde
