### ISSUE TITLE
Ejercicio: ID: SQLALMS-05

### ISSUE THREAD

**Issue by ChristYela** [codingupmyfuture/bootcampduckdb#56]
En este ejercicio, la tabla sale así: 
![image](https://github.com/user-attachments/assets/3569b81c-93b3-4db5-94e3-310db39f2189)

PERO en el resultado de control del pdf sale así: 
![image](https://github.com/user-attachments/assets/10b8be15-a17b-4860-8811-302fe8eaf97f)
 
Y PERO en la respuesta esperada del enunciado sale así:

![image](https://github.com/user-attachments/assets/37606a0e-ba40-48c0-bf56-e3a3c8d0a2cb)

Que pasó aquí (?) : 
![image](https://github.com/user-attachments/assets/f614d179-5b24-4505-b2b3-a1d68c447b8e)

Muchas gracias por sus respuestas.

**Comment by JikaS14** [comment]
Acabe ee responder a esta pregunta en otro post

**Comment by ChristYela** [comment]
@JikaS14 LO vi, pero no entendí y dejé el comentario en el otro post

**Comment by keljozap** [comment]
Hola @ChristYela.

Punto 5. No es necesario crear una tabla temporal para crear el array. El punto te está solicitando crear un array de arrays y no una tabla temporal que devuelva el resultado en string. Por favor revisa tu query.

Saludos!

**Comment by edallanpoe** [comment]
> Hola @ChristYela.
> 
> Punto 5. No es necesario crear una tabla temporal para crear el array. El punto te está solicitando crear un array de arrays y no una tabla temporal que devuelva el resultado en string. Por favor revisa tu query.
> 
> Saludos!

Hola @ChristYela, enhorabuena por tu inventiva y creatividad para resolver el ejercicio, sin embargo, me temo que complicaste el metodo para llegar a la solución. La respuesta es un poco mas de lo que parece: 
```sql
SELECT [['Pan Mimbo', 'Panadería'], ['Roscas Ana', 'Panadería'], ['Fresco hito', 'Bebida'], ['Tanrico', 'Bebida'], ['Menta', NULL], ['Cola-Cola', 'Bebida'], ['Rinse', 'Cuidado personal']] AS inventario
```

Agradezco tu dedicación a la clase.

Cordial saludo.

**Comment by ChristYela** [comment]
@keljozap @edallanpoe Muchas gracias por sus respuestas, a veces la solución puede ser mas sencilla de lo que podría parecer, pese a que el bot estaba configurado de una forma, la forma que yo tenía, podría ser válida, pero el bot tiene una solución más simple. Feliz finde
