### ISSUE TITLE
DUCKDB_SQLSELECT_E28_P20 Pregunta 17 y 18

### ISSUE THREAD

**Issue by DanielaVL** [codingupmyfuture/bootcampduckdb#57]
Creo que hay posibles problemas en la calificación de las preguntas 17 y 18. Al seguir los tips y obtener el resultado esperado, el bot los marca como erróneos. Los errores son de cantidad de resultados pero en los enunciados no hay un límite de resultados que se deban entregar. Por ejemplo, en la pregunta 17, me salen 3660 registros en total y puede que el bot esté tomando menos, pero no se sabe cuánto específicamente.
![image](https://github.com/user-attachments/assets/996cf954-cfbc-4ca8-b6e4-70bf4fe478d5)

Pregunta 17:
![image](https://github.com/user-attachments/assets/9f05f64c-f807-481a-90f2-67ab6955331d)
Longitud estudiante:
![image](https://github.com/user-attachments/assets/d45bf0b7-2c98-405d-a3f8-aaa38b64c270)
Longitud bot:
![image](https://github.com/user-attachments/assets/6e37d430-fb58-4c3f-b1ad-e94c1b16a4ad)

Pregunta 18:
![image](https://github.com/user-attachments/assets/297b2a31-326a-48f7-a634-98de293aaa1b)
![image](https://github.com/user-attachments/assets/cd9db273-c29b-4b03-946f-a3d4417c5af4)
![image](https://github.com/user-attachments/assets/7002d90c-39b6-440c-862c-d36ba4e79e9d)

**Comment by edallanpoe** [comment]
Hola @DanielaVL, agradecemos tu issue, sin embargo, despues de una revisión extensiva tanto del bot como los notebooks y correspondientes enunciados de los punto 17 y 18 respectivamente, encontramos que el error se encuentra en la formulación de los queries:

En el Punto 17: Agregas un limit 100, sin embargo en el ejercicio no se está solicitando limitar la cantidad de registros que debe retornar el query.

En el Punto 18: No filtraste de forma debida las tablas, te comparto este comentario donde se detalla a fondo la razones del error https://github.com/codingupmyfuture/bootcampduckdb/issues/41#issuecomment-2465735413

Agradecemos tu dedicación a la clase.

Saludos cordiales.

**Comment by DanielaVL** [comment]
@edallanpoe Muchas gracias por tu aclaración. Fue tan precisa que pude solucionar correctamente la pregunta 17.
