### ISSUE TITLE
Taller E21_P20 punto 19 y 21

### ISSUE THREAD

**Issue by AlejandroEnciso7** [codingupmyfuture/bootcampduckdb#59]
Hola, nombro dos puntos porque es el mismo error en ambos donde me dice que el nombre de la columna no es unica y por lo tanto mi codigo no se corre en el calificador 
![image](https://github.com/user-attachments/assets/ad747f00-c826-496a-a6b1-36eb49644da7)
![image](https://github.com/user-attachments/assets/5236bd49-1375-405e-acda-47ebe24e0ae6)
Intente cambiar el nombre de las columnas y nuevamente me marco como incorrecto el ejercicio porque ambas no se llamaban 'nombre' como lo espera el control para el punto 19 o 'nombre carrera' para el punto 21 

Desde mi lado el codigo si corre aunque el nombre de las columnas sea el mismo y me otorga los resultados esperados:
para el punto 19:
![image](https://github.com/user-attachments/assets/16b1fa15-5f51-4530-b3ba-28d8c7785749)

y para el punto 21:
![image](https://github.com/user-attachments/assets/1252b078-7fc9-4912-b966-ea885a5af357)
![image](https://github.com/user-attachments/assets/b8a24a74-6dad-4c30-aae5-8ea8b99d217e)
![image](https://github.com/user-attachments/assets/16578250-069f-4ce5-b5a1-1283a4294f72)

Estoy pendiente, gracias!

**Comment by Dhmthe** [comment]
https://github.com/codingupmyfuture/bootcampduckdb/issues/47, Compa mirate este issue, ya dijeron que iban a eliminar esos ejercicios!

**Comment by AlejandroEnciso7** [comment]
Ah @Dhmthe muchas gracias no lo habia visto

**Comment by ChristYela** [comment]
Igual el bot lo sigue calificando como errado, pese a que se haya puesto "iguales" las columnas como alias. En Dbeaver se ve bien, en Collab agregaría _1
