### ISSUE TITLE
DUCKDB_SQLJOIN_E21_P20 Pregunta 5, 19 y 21

### ISSUE THREAD

**Issue by DanielaVL** [codingupmyfuture/bootcampduckdb#60]
Cordial saludo. En estas tres preguntas, el bot requiere que ambas columnas en los resultados tengan el mismo nombre. Sin embargo, esto no es posible ya que, aunque en el código se envían con el mismo nombre, el sistema automáticamente agrega un "1" al final de una de las columnas para diferenciarla. Esta modificación es la causa por la cual el bot considera incorrectos los resultados.

Pregunta 5:
![image](https://github.com/user-attachments/assets/6a234aec-c6f5-4e00-8b2d-6cfcb3556e67)
![image](https://github.com/user-attachments/assets/d82370fe-de92-4513-952d-931655418f02)

Pregunta 19:
![image](https://github.com/user-attachments/assets/c2ae3d1d-0bb2-42b9-b8af-167092c98221)
![image](https://github.com/user-attachments/assets/b99a2ef2-8f18-4457-bbcf-bd68bf7122bc)

Pregunta 21:
![image](https://github.com/user-attachments/assets/8d99e74c-f693-448d-a262-a5c46aebc3ec)
![image](https://github.com/user-attachments/assets/ce42e660-de6f-4b88-89ae-499c679c4a7b)

**Comment by andresgonzalezrpo** [comment]
@DanielaVL yo lo había reportado también y la respuesta fue que los iban a eliminar.

**Comment by juli-amezquita** [comment]
Hola @andresgonzalezrpo, sí, es cierto, habían dicho que las iban a anular pero el bot las sigue calificando como incorrectas y el reporte de notas parciales las sigue considerando dentro del total de respuestas, es decir, aún no lo han corregido.

**Comment by aguirreaida** [comment]
Presento la misma dificultad que la compañera @DanielaVL

**Comment by codingupmyfuture** [comment]
Repetido, todas las notificaciones se realizarán en: #47
