### ISSUE TITLE
DUCKDB_SQL6ADVANCE_E18_P20 Preguntas 13 y 17

### ISSUE THREAD

**Issue by DanielaVL** [codingupmyfuture/bootcampduckdb#61]
Cordial saludo. ¿Podrían, por favor, confirmar si el bot está presentando fallas en estas preguntas? Seguí las indicaciones y obtuve los resultados esperados; sin embargo, fueron calificados como incorrectos. Agradezco de antemano su atención.

Pregunta 13:
![image](https://github.com/user-attachments/assets/9bd69d48-6e4f-4a91-8bc6-ea420b885a53)
![image](https://github.com/user-attachments/assets/994da8dc-8c7c-4b59-b217-ab32fa110186)

Pregunta 17:
![image](https://github.com/user-attachments/assets/bf5f8710-e70c-40bb-b5d8-da88daed7527)

**Comment by ChristYela** [comment]
También me pasa lo mismo. Ni idea de cómo poder solucionarlo.

**Comment by andresgonzalezrpo** [comment]
@DanielaVL en el punto 13 tienes una pequeña diferencia en el ranking rango_multa en la fila 18. Me pasaba algo parecido pero creo que lo puedes solucionar haciendo el ranking de forma DESC.

En el punto 17 si me pasa igual
