### ISSUE TITLE
Taller DUCKDB_SQLJOIN_E21_P20.ipynb problemas de compilacion 

### ISSUE THREAD

**Issue by AndresValenciaC** [codingupmyfuture/bootcampduckdb#62]
Pregunta #1 igual estudiante, control, se colocó como mala la segunda corrección mientras en la primera corrección salio buena.
Pregunta #5 sale codigo estudiante pero sale como no respuesta sale en blanco  en pdf de corrección del taller.
pregunta #14 respuesta estudiante y control iguales en pdf sale incorrecta.
pregunta #19 sale en el pdf el codigo del estudiante y en comparación con la respuesta del Dbeaver es la misma de la de control, sale incorrecta.
pregunta #21 no sale como respondida, sale en código estudiante.
Muchas gracias.

**Comment by codingupmyfuture** [comment]
**IMPORTANTE: El numeral y el número se usa para hacer referencia a otros issues.** 

Los puntos 5, 19, y 21 se resuelven en este https://github.com/codingupmyfuture/bootcampduckdb/issues/47

**Comment by codingupmyfuture** [comment]
Aclarar mejor el puntos 1 y 19, no es claro tu requerimiento
