### ISSUE TITLE
Posible error calificación E22_P10

### ISSUE THREAD

**Issue by Eduard-Atehortua** [codingupmyfuture/bootcampduckdb#63]
Posible error` en taller E22_P10, al calificar ejercicios 2 (total sumas por día) este ejercicio pide poner sumas (plural) pero el bot pide suma (singular), 8 (area círculo), 12 (perimetro area).

![total_suma](https://github.com/user-attachments/assets/4f0e3670-4f35-4407-ad37-e788821dfb09)
![total suma o sumas](https://github.com/user-attachments/assets/d7c1cfe1-99fa-478a-bc23-3b2f492b279a)
![area_circulo](https://github.com/user-attachments/assets/de32f9ac-c25d-4250-908c-a8f90453e925)
![Perímetro_area](https://github.com/user-attachments/assets/bd14f142-9ad4-427e-bf8c-bb13a2e8e156)

**Comment by keljozap** [comment]
Hola @Eduard-Atehortua.

Punto 2. Para el punto 2 por favor utiliza el alias "total suma por dia" de esa forma el evaluador lo tomará como correcto. Para un proximo issue por favor relacionar el nombre del notebook.

Saludos!
