### ISSUE TITLE
Error calificación E22_P10

### ISSUE THREAD

**Issue by Eduard-Atehortua** [codingupmyfuture/bootcampduckdb#64]
Posible error, parecido al a otro en taller E22_P10.  Ejercicio 12. El taller  mayúscula, pero el bot pide minúscula.

![dentro o Dentro](https://github.com/user-attachments/assets/e741a30f-51f1-46b6-8fff-a27122158cd5)
![mayúsculas o minúsculas](https://github.com/user-attachments/assets/4c10fb50-f1aa-43dc-87b5-28ca0189e47e)

**Comment by keljozap** [comment]
Hola @Eduard-Atehortua
Revisando el E22_P10 que indicas, el punto 12 que relacionas no pide ningún caso de verificación de rango. Tal vez sea otro notebook pero con la información que provees es imposible detectar cual es, por favor verifica la información y alza otro issue de ser necesario. Sin esta información no es posible ubicar el notebook, adicional si puedes poner el nombre del notebook seria mucho más sencillo para nosotros ubicar el notebook.

![image](https://github.com/user-attachments/assets/32704e85-3515-428d-b040-d72750451b95)

Saludos!

**Comment by juli-amezquita** [comment]
Hola @Eduard-Atehortua, revisa el issue #52. Espero te ayude.

**Comment by Eduard-Atehortua** [comment]
Perdón, era el 21

**Comment by keljozap** [comment]
Hola @Eduard-Atehortua

Punto 21. El enunciado del ejercicio expresa que debe ser en minúscula 
![image](https://github.com/user-attachments/assets/ea7671a3-042d-43bd-868f-95cd3df6d515)
Y el bot también lo califica con la minúscula.
La tabla de referencia es la que está en mayúscula pero esta solo contempla una idea aproximada de la respuesta, por tanto, es el enunciado el que debe tomarse en cuenta.

Saludos!
