### ISSUE TITLE
ERROR E21_P20.ipynb

### ISSUE THREAD

**Issue by Fenix018** [codingupmyfuture/bootcampduckdb#65]
Buenas tardes, he estado intentando hacer la entrega del trabajo E21_P20.ipynb, pero por alguna razón me devuelve la entrega como inválida aun removiendo los ejercicios 5, 19 y 21, no sé que más hacer para solucionar este problema...

**Comment by JikaS14** [comment]
tengo el mismo problema 
![imagen](https://github.com/user-attachments/assets/624a8cbe-161a-4daa-a8e1-c440390254ad)
y como se remueve los ejercicios? (perdonaran la ignorancia....)

**Comment by Fenix018** [comment]
Ya logré solucionar, los ejercicios se quitan literalmente eliminando las celdas, cuando haces click en una aparecen las opciones.
![image](https://github.com/user-attachments/assets/7d7dbad0-0090-43a4-9298-ba11b8d49802)

**Comment by JikaS14** [comment]
Lo había sospechado desde un principio, pero no quise molestar a doña anaconda y sus pip. gracias por la ilustracion.
