### ISSUE TITLE
Taller DUCKDB_SQLJOIN_E21_P20.ipynb Ejercicio 15

### ISSUE THREAD

**Issue by dcanosu** [codingupmyfuture/bootcampduckdb#66]
En el pto 15, validando los average de los datos de la base de datos me esta dando diferente a la respuesta de control, no sé si estoy cometiendo algun error en el calculo.

![image](https://github.com/user-attachments/assets/48c22e9b-0062-4f81-8a86-5818bdaa91a1)

**Comment by keljozap** [comment]
Hola @dcanosu 

La tabla de referencia del ejercicio no está indicando que solo sean esos tres colegios, si ves en la parte de abajo de la tabla hay unos ..., esto indica que son más resultados pero para referencia solo se muestran los primeros tres, por lo cual no tienes que filtrar por el nombre del colegio.
Adicional no tienes que hacer ROUND de un AVG ya que solo se pide mostrar los puntajes de los colegios sin ninguna operación adicional.

La consulta respuesta es mucho más sencilla de la que tienes.

Espero la respuesta re sirva.

Saludos!

**Comment by dcanosu** [comment]
HOla Keli, cómo estás? filtre por los 3 colegios para compararlos con la respuesta de control y poner el issue dado que los avg que estoy obteniendo son diferentes. 

El ROUND lo utilice dado que en la respuesta de control aparece solamente INT sin los decimales

![image](https://github.com/user-attachments/assets/935eedcf-e427-4f3e-becd-80be9a341d15)

**Comment by Dhmthe** [comment]
Hola @dcanosu compa en ningún momento se pide el promedio, por eso no te coincide con los resultados, solo se pide los puntajes relacionados con el colegio, te muestro mi respuesta así tal vez te des una idea 
![image](https://github.com/user-attachments/assets/e6dce16b-c450-426d-86b8-837f449dce1e)

**Comment by dcanosu** [comment]
Bro, thank you por la aclaración, ya organice la query 100% funcional, Keli mil gracias a ti también :) see you tomorrow
