### ISSUE TITLE
Pertenece el Motor de BD al SGDB

### ISSUE THREAD

**Issue by Yesid4Code** [codingupmyfuture/bootcampduckdb#8]
En BD el motor de una BD y el Gestor (SGBD) son tomados como sinónimos, sin embargo, con el objetivo de conocer la diferencia entre estos dos conceptos y sus diferentes funcionalidades quiero tener claro el siguiente punto.

El motor de una BD pertenece a la BD o al SGBD?

Gracias.

**Comment by luisvasv-teck** [comment]
El motor de una base de datos pertenece al SGBD (Sistema de Gestión de Bases de Datos). Es el componente que se encarga de manejar las operaciones internas de la base de datos, como el almacenamiento, la recuperación y la gestión de los datos. La base de datos en sí es solo el conjunto de datos organizados, mientras que el SGBD es el software que gestiona y utiliza el motor para interactuar con esos datos.
